/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.clases.*;
import com.interfaz.*;
import java.awt.Color;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.clases.Catering;
import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Comida;
import com.clases.Direccion;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Restaurante;
import com.clases.Venta;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


public class AltaComida extends javax.swing.JFrame {

    private AltaRestaurante altaRestaurante;
    private String nombreFotografia;
    int xMouse, yMouse;

    /**
     * Creates new form AltaComida
     */
    public AltaComida(AltaRestaurante altaRestaurante) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */

        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            System.err.println("Failed to initialize LaF");

            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    System.out.println(info.getName());
                    if ("Flatlaf".equals(info.getName())) {
                        System.out.println("Flatlaf look and feel stablished");
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold> //Establece el Flat-Laf look and feel (Dependencia)
        initComponents();
        this.altaRestaurante = altaRestaurante;
        this.setLocationRelativeTo(null);
        jComida.setText("Comida " + String.valueOf(altaRestaurante.getAvailableIdComida()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonAnadirImagen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jIcon = new javax.swing.JLabel();
        jNombre = new javax.swing.JTextField();
        txtNombre = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JLabel();
        jPrecio = new javax.swing.JFormattedTextField();
        jSeparadorPrecio = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollComida = new javax.swing.JScrollPane();
        jIngredientes = new javax.swing.JTextArea();
        txtIngredientes = new javax.swing.JLabel();
        jComida = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 153, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(255, 153, 102));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo2.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(javaeatlogo1)
                .addGap(97, 97, 97)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaeatlogo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Añadir imagen:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 140, 30));

        jButtonAnadirImagen.setBackground(new java.awt.Color(164, 204, 222));
        jButtonAnadirImagen.setFont(new java.awt.Font("Roboto Condensed", 2, 16)); // NOI18N
        jButtonAnadirImagen.setForeground(new java.awt.Color(51, 51, 51));
        jButtonAnadirImagen.setText("AÑADIR");
        jButtonAnadirImagen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAnadirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirImagenActionPerformed(evt);
            }
        });
        bg.add(jButtonAnadirImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 100, 20));

        jPanel3.setBackground(new java.awt.Color(204, 218, 234));
        jPanel3.setMaximumSize(new java.awt.Dimension(373, 142));
        jPanel3.setMinimumSize(new java.awt.Dimension(373, 142));

        jIcon.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
        );

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 350, -1));

        jNombre.setBackground(new java.awt.Color(204, 218, 234));
        jNombre.setBorder(null);
        bg.add(jNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 230, -1));

        txtNombre.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre:");
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, 20));

        txtPrecio.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(51, 51, 51));
        txtPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPrecio.setText("Precio:");
        bg.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 50, 20));

        jPrecio.setBackground(new java.awt.Color(204, 218, 234));
        jPrecio.setBorder(null);
        jPrecio.setForeground(new java.awt.Color(51, 51, 51));
        jPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrecioActionPerformed(evt);
            }
        });
        bg.add(jPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 80, -1));

        jSeparadorPrecio.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparadorPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, 10));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 230, 10));

        jIngredientes.setBackground(new java.awt.Color(204, 218, 234));
        jIngredientes.setColumns(20);
        jIngredientes.setForeground(new java.awt.Color(51, 51, 51));
        jIngredientes.setRows(5);
        jScrollComida.setViewportView(jIngredientes);

        bg.add(jScrollComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 250, 50));

        txtIngredientes.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtIngredientes.setForeground(new java.awt.Color(0, 0, 0));
        txtIngredientes.setText("Ingredientes:");
        bg.add(txtIngredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 90, 20));

        jComida.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jComida.setForeground(new java.awt.Color(51, 51, 51));
        jComida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jComida.setText("Comida 1");
        bg.add(jComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 50));

        jButtonGuardar.setBackground(new java.awt.Color(255, 118, 41));
        jButtonGuardar.setFont(new java.awt.Font("Roboto Condensed", 2, 16)); // NOI18N
        jButtonGuardar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        bg.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jButtonCancelar.setBackground(new java.awt.Color(255, 118, 41));
        jButtonCancelar.setFont(new java.awt.Font("Roboto Condensed", 2, 16)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(51, 51, 51));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        bg.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 480, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 389, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void jButtonAnadirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirImagenActionPerformed
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.jpg", "jpg");
        fc.setFileFilter(filter);
        int selection = fc.showOpenDialog(this);
        if (selection == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            BufferedImage image;
            try {
                image = ImageIO.read(file);
            } catch (IOException e) {
                System.out.print("Error IO: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Elige una imagen válida", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            File outputImage;

            outputImage = new File("src/main/resources/otro/RESTAURANTE" + altaRestaurante.getRestaurante().getId() + "/COMIDA" + altaRestaurante.getAvailableIdComida() + ".jpg");
            nombreFotografia = "src/main/resources/otro/RESTAURANTE" + altaRestaurante.getRestaurante().getId() + "/COMIDA" + altaRestaurante.getAvailableIdComida() + ".jpg";

            try {
                boolean write = ImageIO.write(image, "jpg", outputImage);
                System.out.println(write);
            } catch (IOException e) {
                System.out.print("Error IO: " + e.getMessage());
                JOptionPane.showMessageDialog(this, "Elige una imagen válida", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ImageIcon icon = Restaurante.resizedIcon(jIcon.getBounds().width, jIcon.getBounds().height, file.getAbsolutePath());
            if (icon != null) {
                jIcon.setIcon(icon);
            }
        }
    }//GEN-LAST:event_jButtonAnadirImagenActionPerformed

    private void jPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPrecioActionPerformed


    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        //Datos Empresa
        String nombre = jNombre.getText();
        String precioTemp = jPrecio.getText();
        String ingredientes = jIngredientes.getText();

        if (nombre.isEmpty() || precioTemp.isEmpty() || ingredientes.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduzca todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nombreFotografia == null) {
            JOptionPane.showMessageDialog(this, "Por favor, introduzca una imagen", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Double precio = MainManager.verificaPrecio(precioTemp);
        if (precio < 0) {
            JOptionPane.showMessageDialog(this, "Por favor, introduzca un precio válido", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Comida comida = new Comida(nombre, precio, nombreFotografia, ingredientes, altaRestaurante.getAvailableIdComida());

        altaRestaurante.addtoListaComida(comida);
        this.setVisible(false);
        altaRestaurante.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        this.setVisible(false);
        this.dispose();
        altaRestaurante.setVisible(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaComida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaComida(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonAnadirImagen;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JLabel jComida;
    private javax.swing.JLabel jIcon;
    private javax.swing.JTextArea jIngredientes;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jNombre;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField jPrecio;
    private javax.swing.JScrollPane jScrollComida;
    private javax.swing.JSeparator jSeparadorPrecio;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JLabel txtIngredientes;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtPrecio;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
