/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.*;
import java.awt.Color;
import javax.swing.JOptionPane;


public class Clientes extends javax.swing.JPanel {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtCorreo = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        txtDNI = new javax.swing.JLabel();
        txtNumero = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtDatosPers = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JLabel();
        fCorreo = new javax.swing.JTextField();
        fCalle = new javax.swing.JTextField();
        fCiudad = new javax.swing.JTextField();
        fClave = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        txtNombre1 = new javax.swing.JLabel();
        cuentatxt = new javax.swing.JLabel();
        logintxt = new javax.swing.JLabel();
        pSiguiente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fDNI = new javax.swing.JFormattedTextField();
        fCodPostal = new javax.swing.JFormattedTextField();
        fNum = new javax.swing.JFormattedTextField();
        fApellidos = new javax.swing.JTextField();
        fNombre = new javax.swing.JTextField();
        fTelefono = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(700, 420));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(700, 470));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCorreo.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo");
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));

        txtCalle.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle");
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        txtCodPostal.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCodPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal.setText("Código Postal");
        bg.add(txtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        txtApellido.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setText("Apellidos");
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        txtDNI.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtDNI.setForeground(new java.awt.Color(0, 0, 0));
        txtDNI.setText("DNI / NIE");
        bg.add(txtDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        txtNumero.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.setText("Nº");
        bg.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        txtCiudad.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad");
        bg.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        txtDatosPers.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        txtDatosPers.setForeground(new java.awt.Color(0, 0, 0));
        txtDatosPers.setText("DATOS PERSONALES");
        bg.add(txtDatosPers, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setText("DIRECCIÓN");
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(0, 0, 0));
        txtTelefono.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Telefono");
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        txtContrasena.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtContrasena.setForeground(new java.awt.Color(0, 0, 0));
        txtContrasena.setText("Contraseña");
        bg.add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        fCorreo.setBackground(new java.awt.Color(255, 255, 255));
        fCorreo.setForeground(new java.awt.Color(51, 51, 51));
        fCorreo.setBorder(null);
        bg.add(fCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 260, -1));

        fCalle.setBackground(new java.awt.Color(255, 255, 255));
        fCalle.setForeground(new java.awt.Color(51, 51, 51));
        fCalle.setBorder(null);
        bg.add(fCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, -1));

        fCiudad.setBackground(new java.awt.Color(255, 255, 255));
        fCiudad.setForeground(new java.awt.Color(51, 51, 51));
        fCiudad.setBorder(null);
        fCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCiudadActionPerformed(evt);
            }
        });
        bg.add(fCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 180, -1));

        fClave.setBackground(new java.awt.Color(255, 255, 255));
        fClave.setForeground(new java.awt.Color(51, 51, 51));
        fClave.setBorder(null);
        bg.add(fClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 220, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 210, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 130, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 180, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 260, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 160, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 260, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 70, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 180, 10));

        jSeparator9.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 220, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 90, 10));

        txtNombre1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre1.setText("Nombre");
        bg.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        cuentatxt.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        cuentatxt.setForeground(new java.awt.Color(51, 51, 51));
        cuentatxt.setText("¿Tienes una cuenta ya?");
        bg.add(cuentatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        logintxt.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        logintxt.setForeground(new java.awt.Color(238, 88, 88));
        logintxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logintxt.setText("Iniciar sesión");
        logintxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logintxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logintxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logintxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logintxtMouseExited(evt);
            }
        });
        bg.add(logintxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 110, 20));

        pSiguiente.setBackground(new java.awt.Color(238, 88, 88));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SIGUIENTE");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pSiguienteLayout = new javax.swing.GroupLayout(pSiguiente);
        pSiguiente.setLayout(pSiguienteLayout);
        pSiguienteLayout.setHorizontalGroup(
            pSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        pSiguienteLayout.setVerticalGroup(
            pSiguienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(pSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 150, -1));

        fDNI.setBackground(new java.awt.Color(255, 255, 255));
        fDNI.setBorder(null);
        fDNI.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fDNI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("A#######U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        bg.add(fDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 160, -1));

        fCodPostal.setBackground(new java.awt.Color(255, 255, 255));
        fCodPostal.setBorder(null);
        fCodPostal.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fCodPostal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fCodPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCodPostalActionPerformed(evt);
            }
        });
        bg.add(fCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 90, -1));

        fNum.setBackground(new java.awt.Color(255, 255, 255));
        fNum.setBorder(null);
        fNum.setForeground(new java.awt.Color(51, 51, 51));
        fNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNumActionPerformed(evt);
            }
        });
        bg.add(fNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 70, -1));

        fApellidos.setBackground(new java.awt.Color(255, 255, 255));
        fApellidos.setForeground(new java.awt.Color(51, 51, 51));
        fApellidos.setBorder(null);
        bg.add(fApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 210, -1));

        fNombre.setBackground(new java.awt.Color(255, 255, 255));
        fNombre.setForeground(new java.awt.Color(51, 51, 51));
        fNombre.setBorder(null);
        bg.add(fNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 180, -1));

        fTelefono.setBackground(new java.awt.Color(255, 255, 255));
        fTelefono.setBorder(null);
        fTelefono.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTelefonoActionPerformed(evt);
            }
        });
        bg.add(fTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void fCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCiudadActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        //Datos Cliente
        String nombre = fNombre.getText();
        String apellido = fApellidos.getText();
        String dni = fDNI.getText();
        String correo = fCorreo.getText();
        String telefono = fTelefono.getText();
        String clave = String.valueOf(fClave.getPassword());
        
        //Dirección
        String calle = fCalle.getText();
        String codPostal = fCodPostal.getText();
        String num = fNum.getText();
        String ciudad = fCiudad.getText();

        if (nombre.equals("") || dni.equals("") || correo.equals("") || telefono.equals("") ||
                apellido.equals("") || clave.equals("") || calle.equals("") || codPostal.equals("") ||
                num.equals("") || ciudad.equals(""))
            
        {
            JOptionPane.showMessageDialog(this, "Introduzca todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Cliente cliente;
        Direccion direccion = new Direccion(calle, num, codPostal, ciudad);
        ClienteParticular particular = new ClienteParticular(dni,nombre,apellido,direccion,telefono,correo,clave,MainManager.getClientes().size()+1);
            cliente = particular;
        
        String msg = MainManager.verificaRegister(cliente);
        if (!msg.equals("")) {
            JOptionPane.showMessageDialog(this, msg, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jLabel1MouseClicked

    private void fCodPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCodPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCodPostalActionPerformed

    private void fNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNumActionPerformed

    private void fTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTelefonoActionPerformed

    private void logintxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintxtMouseExited

        logintxt.setForeground(new Color(255,135,83));
    }//GEN-LAST:event_logintxtMouseExited

    private void logintxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintxtMouseEntered
        logintxt.setForeground(new Color(255,102,0));
    }//GEN-LAST:event_logintxtMouseEntered

    private void logintxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logintxtMouseClicked
        MainManager.showFrame("Login");
    }//GEN-LAST:event_logintxtMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cuentatxt;
    private javax.swing.JTextField fApellidos;
    private javax.swing.JTextField fCalle;
    private javax.swing.JTextField fCiudad;
    private javax.swing.JPasswordField fClave;
    private javax.swing.JFormattedTextField fCodPostal;
    private javax.swing.JTextField fCorreo;
    private javax.swing.JFormattedTextField fDNI;
    private javax.swing.JTextField fNombre;
    private javax.swing.JFormattedTextField fNum;
    private javax.swing.JFormattedTextField fTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel logintxt;
    private javax.swing.JPanel pSiguiente;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCodPostal;
    private javax.swing.JLabel txtContrasena;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDNI;
    private javax.swing.JLabel txtDatosPers;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNumero;
    private javax.swing.JLabel txtTelefono;
    // End of variables declaration//GEN-END:variables
}
