/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.clases.CarritoCompra;
import com.clases.Catering;
import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Comida;
import com.clases.Direccion;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Menu;
import com.clases.Restaurante;
import com.clases.Venta;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import javax.swing.JOptionPane;

public class Comprar extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private Restaurante restaurante;
    private CarritoCompra carrito;
    private ArrayList<TemplateCarrito> listaTemplatesCom = new ArrayList<>();
    private ArrayList<TemplateCarrito> listaTemplatesMenu = new ArrayList<>();
    private ArrayList<TemplateCarrito> listaTemplatesCatCarrito = new ArrayList<>();
    private double precioVenta;
    private VerRestaurante verRestaurante;

    /**
     * Creates new form Comprar
     *
     * @param restauranteActual
     * @param verRestaurante
     */
    public Comprar(Restaurante restauranteActual, VerRestaurante verRestaurante) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.restaurante = restauranteActual;
        this.verRestaurante = verRestaurante;
        rellenarDatos();
        this.carrito = MainManager.getCarritoCompra();
        actualizarListaCarrito(carrito);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();
        scroll2 = new javax.swing.JScrollPane();
        panel2 = new javax.swing.JPanel();
        jButtonComprar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JLabel();
        txtTitulo3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JLabel();
        txtWeb = new javax.swing.JLabel();
        txtNumero = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtDatos = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        txtNombre1 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JLabel();
        fNombre = new javax.swing.JTextField();
        fCorreo = new javax.swing.JTextField();
        fWebApellido = new javax.swing.JTextField();
        fTelefono = new javax.swing.JFormattedTextField();
        fCalle = new javax.swing.JTextField();
        fCodPostal = new javax.swing.JFormattedTextField();
        fCiudad = new javax.swing.JTextField();
        fNum = new javax.swing.JFormattedTextField();
        precioTotal = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        gastos1 = new javax.swing.JLabel();
        precio1 = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        descuento1 = new javax.swing.JLabel();
        gastos = new javax.swing.JLabel();
        precioTotal1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(1250, 60));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(255, 255, 255));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo2.png"))); // NOI18N

        flecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/flecha (3).png"))); // NOI18N
        flecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(flecha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(javaeatlogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 742, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(javaeatlogo1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 50));

        scroll2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panel2.setBackground(new java.awt.Color(255, 153, 102));
        panel2.setLayout(new javax.swing.BoxLayout(panel2, javax.swing.BoxLayout.Y_AXIS));
        scroll2.setViewportView(panel2);

        bg.add(scroll2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 300, 500));

        jButtonComprar.setBackground(new java.awt.Color(255, 153, 102));
        jButtonComprar.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        jButtonComprar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonComprar.setText("COMPRAR");
        jButtonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarActionPerformed(evt);
            }
        });
        bg.add(jButtonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 570, 280, 50));

        txtTitulo.setFont(new java.awt.Font("Roboto Condensed Light", 2, 24)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtTitulo.setText("RESUMEN DEL PEDIDO");
        bg.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, 300, 50));

        txtTitulo3.setFont(new java.awt.Font("Roboto Condensed Light", 2, 24)); // NOI18N
        txtTitulo3.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo3.setText("RESUMEN DEL COMPRADOR");
        bg.add(txtTitulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 270, 50));

        txtCorreo.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo");
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        txtCalle.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle");
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, -1, -1));

        txtCodPostal.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCodPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal.setText("Código Postal");
        bg.add(txtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        txtWeb.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtWeb.setForeground(new java.awt.Color(0, 0, 0));
        txtWeb.setText("WEB");
        bg.add(txtWeb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        txtNumero.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        txtNumero.setText("Nº");
        bg.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        txtCiudad.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad");
        bg.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        txtDatos.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        txtDatos.setForeground(new java.awt.Color(0, 0, 0));
        txtDatos.setText("DATOS DEL COMPRADOR");
        bg.add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        txtDireccion.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        txtDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txtDireccion.setText("DIRECCIÓN DE ENVÍO");
        bg.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, -1));

        txtTelefono.setBackground(new java.awt.Color(0, 0, 0));
        txtTelefono.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Telefono");
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 210, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 180, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 260, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 260, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 70, 10));

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 180, 10));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));
        bg.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 400, 90, 10));

        txtNombre1.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre1.setText("Nombre");
        bg.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        txtApellido.setFont(new java.awt.Font("Roboto Condensed", 0, 12)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtApellido.setText("Apellidos");
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        fNombre.setBackground(new java.awt.Color(255, 255, 255));
        fNombre.setForeground(new java.awt.Color(51, 51, 51));
        fNombre.setBorder(null);
        bg.add(fNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 180, -1));

        fCorreo.setBackground(new java.awt.Color(255, 255, 255));
        fCorreo.setForeground(new java.awt.Color(51, 51, 51));
        fCorreo.setBorder(null);
        bg.add(fCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 260, -1));

        fWebApellido.setBackground(new java.awt.Color(255, 255, 255));
        fWebApellido.setForeground(new java.awt.Color(51, 51, 51));
        fWebApellido.setBorder(null);
        bg.add(fWebApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 210, -1));

        fTelefono.setBackground(new java.awt.Color(255, 255, 255));
        fTelefono.setBorder(null);
        fTelefono.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fTelefonoActionPerformed(evt);
            }
        });
        bg.add(fTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 130, -1));

        fCalle.setBackground(new java.awt.Color(255, 255, 255));
        fCalle.setForeground(new java.awt.Color(51, 51, 51));
        fCalle.setBorder(null);
        bg.add(fCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 260, -1));

        fCodPostal.setBackground(new java.awt.Color(255, 255, 255));
        fCodPostal.setBorder(null);
        fCodPostal.setForeground(new java.awt.Color(51, 51, 51));
        try {
            fCodPostal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fCodPostal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCodPostalActionPerformed(evt);
            }
        });
        bg.add(fCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, -1));

        fCiudad.setBackground(new java.awt.Color(255, 255, 255));
        fCiudad.setForeground(new java.awt.Color(51, 51, 51));
        fCiudad.setBorder(null);
        fCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fCiudadActionPerformed(evt);
            }
        });
        bg.add(fCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 180, -1));

        fNum.setBackground(new java.awt.Color(255, 255, 255));
        fNum.setBorder(null);
        fNum.setForeground(new java.awt.Color(51, 51, 51));
        fNum.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        fNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNumActionPerformed(evt);
            }
        });
        bg.add(fNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 70, -1));

        precioTotal.setFont(new java.awt.Font("Roboto Condensed Light", 0, 22)); // NOI18N
        precioTotal.setForeground(new java.awt.Color(0, 0, 0));
        precioTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precioTotal.setText("35€");
        bg.add(precioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 210, 30));

        descuento.setFont(new java.awt.Font("Roboto Condensed Light", 0, 22)); // NOI18N
        descuento.setForeground(new java.awt.Color(0, 0, 0));
        descuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        descuento.setText("15€");
        bg.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 110, 30));

        gastos1.setFont(new java.awt.Font("Roboto Condensed Light", 0, 20)); // NOI18N
        gastos1.setForeground(new java.awt.Color(0, 0, 0));
        gastos1.setText("Gastos de Envío");
        bg.add(gastos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 180, 30));

        precio1.setFont(new java.awt.Font("Roboto Condensed Light", 0, 20)); // NOI18N
        precio1.setForeground(new java.awt.Color(0, 0, 0));
        precio1.setText("Precio Pedido ");
        bg.add(precio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, -1, 30));

        precio.setFont(new java.awt.Font("Roboto Condensed Light", 0, 22)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precio.setText("10€");
        bg.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 140, 30));

        descuento1.setFont(new java.awt.Font("Roboto Condensed Light", 0, 20)); // NOI18N
        descuento1.setForeground(new java.awt.Color(0, 0, 0));
        descuento1.setText("Descuento por Empresa");
        bg.add(descuento1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, -1, 30));

        gastos.setFont(new java.awt.Font("Roboto Condensed Light", 0, 22)); // NOI18N
        gastos.setForeground(new java.awt.Color(0, 0, 0));
        gastos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        gastos.setText("10€");
        bg.add(gastos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 140, 30));

        precioTotal1.setFont(new java.awt.Font("Roboto Condensed Light", 0, 20)); // NOI18N
        precioTotal1.setForeground(new java.awt.Color(0, 0, 0));
        precioTotal1.setText("Precio Total");
        bg.add(precioTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, 210, 30));
        bg.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 460, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1000, 650);
    }// </editor-fold>//GEN-END:initComponents

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void flechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaMouseClicked
        this.setVisible(false);
        this.dispose();
        verRestaurante.setVisible(true);
        verRestaurante.actualizarRestaurante();
    }//GEN-LAST:event_flechaMouseClicked

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void fTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fTelefonoActionPerformed

    private void fCodPostalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCodPostalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCodPostalActionPerformed

    private void fCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fCiudadActionPerformed

    private void fNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNumActionPerformed

    private void jButtonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarActionPerformed
        ArrayList<Comida> comidas = carrito.getComidas();
        ArrayList<Comida> comidasCopia = new ArrayList<>();
//        Collections.copy(comidas, comidasCopia);

        for (Comida comida : comidas) {
            comidasCopia.add(new Comida(comida));
        }

        ArrayList<Menu> menus = carrito.getMenus();
        ArrayList<Menu> menusCopia = new ArrayList<>();
//        Collections.copy(menus, menusCopia);
        for (Menu menu : menus) {
            menusCopia.add(new Menu(menu));
        }
//        
        ArrayList<String> catering = carrito.getCatering();
        ArrayList<String> cateringCopia = new ArrayList<>();
//        Collections.copy(catering, cateringCopia);
        cateringCopia.addAll(catering);

        comidas.clear();
        Venta venta1 = new Venta(MainManager.getAvailableIdVentas(),LocalDateTime.now(), comidasCopia, menusCopia, cateringCopia, MainManager.getClienteIniciado(), MainManager.getClienteIniciado().getDireccion(), precioVenta, restaurante);
        System.out.println(comidasCopia.size() + " + " + menusCopia.size() + " + " + cateringCopia.size());

        String numTarjeta = MainManager.getClienteIniciado().getTarjeta().getNumTarjeta();
        int lenNum = numTarjeta.length();
        String tarjetaTxt = "";
        for (int i = 0; i < lenNum - 4; i++) {
            tarjetaTxt += "*";
        }
        tarjetaTxt += numTarjeta.substring(lenNum - 4);
        JOptionPane.showMessageDialog(this, "Compra realizada con éxito.\n Pago realizado con tarjeta: " + tarjetaTxt, "", JOptionPane.INFORMATION_MESSAGE);

        //Registramos la venta
        MainManager.registrarVenta(venta1);
        //System.out.println(venta1.getComidasCompradas().size());
        MainManager.limpiarCarrito();

        //updateProductList();
        verRestaurante.dispose();
        this.setVisible(false);
        this.dispose();
        MainManager.showFrame("MenuPrincipal");
    }//GEN-LAST:event_jButtonComprarActionPerformed

    private void rellenarDatos() {
        Cliente cliente = MainManager.getClienteIniciado();
        if (cliente instanceof ClienteParticular) {
//            txtDatos.setText("DATOS PERSONALES");
//            fCifDni.setText(((ClienteParticular) cliente).getDni());
            fWebApellido.setText(((ClienteParticular) cliente).getApellido());
//            txtCIF.setText("");
            txtWeb.setText("");
        } else {
//            txtDatos.setText("DATOS EMPRESA");
//            fCifDni.setText(((Empresa) cliente).getCif());
            fWebApellido.setText(((Empresa) cliente).getWeb());
//            txtDNI.setText("");
            txtApellido.setText("");
        }
        //Datos Empresa
        fNombre.setText(cliente.getNombre());
        fCorreo.setText(cliente.getCorreo());
        fTelefono.setText(cliente.getTelefono());
//        fClave.setText("");
//        fClaveNueva.setText("");

        //Dirección
        Direccion direccion = cliente.getDireccion();
        fCalle.setText(direccion.getCalle());
        fNum.setText(direccion.getNumero());
        fCodPostal.setText(direccion.getCodigoPostal());
        fCiudad.setText(direccion.getCiudad());
    }

    public void generarPanelesCarrito() {
//        int numComidas = carrito.getComidas().size();
//        int numMenus = carrito.getMenus().size();
        //int numTotal = numComidas + numMenus /* + numCatering o algo así */;
        for (Comida comida : carrito.getComidas()) {
            TemplateCarrito template = new TemplateCarrito();
            listaTemplatesCom.add(template);
            panel2.add(template);
        }
        for (Menu menu : carrito.getMenus()) {
            TemplateCarrito template = new TemplateCarrito();
            listaTemplatesMenu.add(template);
            panel2.add(template);
        }
        for (String servicio : carrito.getCatering()) {
            TemplateCarrito template = new TemplateCarrito();
            listaTemplatesCatCarrito.add(template);
            panel2.add(template);
        }

        panel2.revalidate();
        panel2.repaint();
        scroll2.repaint();
    }

    public void actualizarPanel() {
        panel2.removeAll();
        panel2.revalidate();
        panel2.repaint();
        listaTemplatesCom.clear();
        listaTemplatesMenu.clear();
        listaTemplatesCatCarrito.clear();
    }

    public void actualizarListaCarrito(CarritoCompra carrito) {

        actualizarPanel();
        descuento.setVisible(false);
        descuento1.setVisible(false);
        this.carrito = carrito;
        generarPanelesCarrito();
        rellenarPanelesCarrito();

        double precioCompra = carrito.precioCompra(restaurante);
        precio.setText("+" + precioCompra + "€");
        gastos.setText("+" + restaurante.getGastosEnvio() + "€");
        if (MainManager.getClienteIniciado() instanceof Empresa) {
            descuento.setVisible(true);
            descuento1.setVisible(true);
            descuento.setText("-" + String.format("%.2f%n", precioCompra * 0.10) + "€");
            precioTotal.setText(String.format("%.2f%n", precioCompra * 0.90 + restaurante.getGastosEnvio()) + "€");
            precioVenta = precioCompra * 0.90 + restaurante.getGastosEnvio();
            BigDecimal bd = new BigDecimal(precioVenta);
            bd = bd.setScale(2, RoundingMode.HALF_UP);
            precioVenta = bd.doubleValue();

        } else {
            precioTotal.setText(String.format("%.2f%n", precioCompra + restaurante.getGastosEnvio()) + "€");
            precioVenta = precioCompra + restaurante.getGastosEnvio();
            BigDecimal bd = new BigDecimal(precioVenta);
            bd = bd.setScale(2, RoundingMode.HALF_UP);
            precioVenta = bd.doubleValue();

        }
    }

    public void rellenarPanelesCarrito() {
        int i = 0;
        System.out.println(listaTemplatesCom.size());
        for (TemplateCarrito template : listaTemplatesCom) {
            Comida comida = carrito.getComidas().get(i);
            template.setTitulo(comida.getTitulo());
            template.setPrecio(comida.getPrecioVenta() * comida.getCantidad());
            template.setCantidad(comida.getCantidad());
            //template.setBorder(new LineBorder(Color.blue)); //Pintamos de azul para ver lo limites
            i++;
        }
        System.out.println(carrito.getMenus().size());
        int j = 0;
        for (TemplateCarrito template : listaTemplatesMenu) {
            Menu menu = carrito.getMenus().get(j);
            template.setTitulo(menu.getNombre());
            template.setPrecio(menu.getPrecio() * menu.getCantidad());
            template.setCantidad(menu.getCantidad());
            //template.setBorder(new LineBorder(Color.blue)); //Pintamos de azul para ver lo limites
            j++;
        }
        //zona del catering i guess
        int z = 0;
        Catering cat = restaurante.getCatering();
        for (TemplateCarrito template : listaTemplatesCatCarrito) {
            String nombre = carrito.getCatering().get(z);
            template.setServicio(nombre);
            template.setPrecio(cat.getPrecioServicios(nombre));
            template.setCantidad(1);
            z++;
        }
        System.out.println("Terminado");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                //new Comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel descuento1;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JTextField fCalle;
    private javax.swing.JTextField fCiudad;
    private javax.swing.JFormattedTextField fCodPostal;
    private javax.swing.JTextField fCorreo;
    private javax.swing.JTextField fNombre;
    private javax.swing.JFormattedTextField fNum;
    private javax.swing.JFormattedTextField fTelefono;
    private javax.swing.JTextField fWebApellido;
    private javax.swing.JLabel flecha;
    private javax.swing.JLabel gastos;
    private javax.swing.JLabel gastos1;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButtonComprar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel precio1;
    private javax.swing.JLabel precioTotal;
    private javax.swing.JLabel precioTotal1;
    private javax.swing.JScrollPane scroll2;
    private javax.swing.JLabel txtApellido;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCodPostal;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtDatos;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNumero;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtTitulo;
    private javax.swing.JLabel txtTitulo3;
    private javax.swing.JLabel txtWeb;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
