/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.MainManager;
import com.clases.Venta;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import java.util.ArrayList;
import java.util.GregorianCalendar;
import javax.swing.JButton;
import com.interfaz.ContenidoVenta;


public class ConsultaVentas extends javax.swing.JPanel {

    private LocalDate fechaCalendario;
    private boolean ordenPorFecha;
    private Venta ventaElegida;

    /**
     * Creates new form ConsultaVentas
     */
    public ConsultaVentas() {
        initComponents();
        jDatePicker2.setVisible(false);
        jRadioButton1.setVisible(true);
        jRadioButton2.setVisible(true);
        actualizarLista(MainManager.getVentas());
        //Venta venta = MainManager.getVentas().get(1);
        //System.out.println(venta.getComidasCompradas().size() + "|" + venta.getMenusComprados().size() + "|" + venta.getCateringComprados().size());
        ordenPorFecha = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelContenido = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jDatePicker2 = new org.jdatepicker.JDatePicker();

        setBackground(new java.awt.Color(204, 218, 234));

        jPanel1.setBackground(new java.awt.Color(204, 218, 234));

        jLabel1.setFont(new java.awt.Font("Roboto Condensed Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Ventas");

        jPanelContenido.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenido.setLayout(new javax.swing.BoxLayout(jPanelContenido, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(jPanelContenido);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Todas las Ventas");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setForeground(new java.awt.Color(51, 51, 51));
        jRadioButton2.setText("A partir de una fecha");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));

        jDatePicker2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDatePicker2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton2)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 69, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jDatePicker2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarLista(ArrayList<Venta> ventas) {
        jPanelContenido.removeAll();
        for (Venta venta : ventas) {
            System.out.println(venta.getComidasCompradas().size() + "|" + venta.getMenusComprados().size() + "|" + venta.getCateringComprados().size());
            JButton jbutton = new JButton();
            jbutton.setFont(new java.awt.Font("Segoe UI", 0, 15));
            jbutton.setText("Venta " + venta.getId() + " | " + " Fecha de venta: " + venta.getFechaVenta().toLocalDate().format(DateTimeFormatter.ofLocalizedDate(FormatStyle.SHORT)));
            jbutton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jbutton.setMaximumSize(new java.awt.Dimension(696, 100));
            jbutton.setMinimumSize(new java.awt.Dimension(0, 0));
            jbutton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ventaElegida = venta;
                    jButtonActionPerformed();
                }
            });
            jPanelContenido.add(jbutton);
        }
        jPanelContenido.revalidate();
        jPanelContenido.repaint();
    }
    
    private void updateVentasByDate(){
	ArrayList<Venta> ventasDeFecha = new ArrayList<>();
	for(Venta venta : MainManager.getVentas()){
	    if(venta.getFechaVenta().toLocalDate().isAfter(fechaCalendario) || venta.getFechaVenta().toLocalDate().isEqual(fechaCalendario)){
		ventasDeFecha.add(venta);
	    }
	}
	actualizarLista(ventasDeFecha);
    }
    
    public Venta getVentaActual() {
        return ventaElegida;
    }
    
    private void jButtonActionPerformed() {
        ContenidoVenta contenidoVenta = new ContenidoVenta(this);
        MainManager.showPanel(contenidoVenta, 670, 427, jPanelContenido);
        jRadioButton1.setVisible(false);
        jRadioButton2.setVisible(false);
        jDatePicker2.setVisible(false);

    }
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        jDatePicker2.setVisible(false);
        actualizarLista(MainManager.getVentas());
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jDatePicker2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDatePicker2ActionPerformed
        GregorianCalendar date = (GregorianCalendar) jDatePicker2.getModel().getValue();
        if(date != null){
            LocalDate localDate = LocalDate.ofInstant(date.toInstant(), ZoneId.systemDefault());
        fechaCalendario = localDate;
        if(ordenPorFecha){
            updateVentasByDate();
        }
        }else{
            actualizarLista(MainManager.getVentas());
        }
    }//GEN-LAST:event_jDatePicker2ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        jDatePicker2.setVisible(true);
        ordenPorFecha = true;
        if(fechaCalendario != null){
            updateVentasByDate();
        }

    }//GEN-LAST:event_jRadioButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private org.jdatepicker.JDatePicker jDatePicker2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContenido;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
