/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.Catering;
import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Comida;
import com.clases.Direccion;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Menu;
import com.clases.Restaurante;
import com.clases.Venta;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


public class ContenidoRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form contenidoVenta
     */
    public ContenidoRestaurante(Restaurante restaurante) {
        initComponents();
        actualizarDatos(restaurante);
        actualizarLista(restaurante.getComidas(), restaurante.getMenus());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        txtCategoria = new javax.swing.JLabel();
        txtCategoria1 = new javax.swing.JLabel();
        txtCif1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtCif = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListMenus = new javax.swing.JList<>();
        jCatering = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComida = new javax.swing.JLabel();
        txtCamareros = new javax.swing.JLabel();
        jCamareros = new javax.swing.JLabel();
        jEspacio = new javax.swing.JLabel();
        jCocineros = new javax.swing.JLabel();
        txtComida = new javax.swing.JLabel();
        txtCocineros = new javax.swing.JLabel();
        txtEspacio = new javax.swing.JLabel();
        jDecoracion = new javax.swing.JLabel();
        txtDecoracion = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JLabel();
        txtNum = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtCalle1 = new javax.swing.JLabel();
        txtCodPostal1 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtCiudad1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jRestaurante = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListComidas = new javax.swing.JList<>();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCategoria.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCategoria.setForeground(new java.awt.Color(0, 0, 0));
        txtCategoria.setText("Categoria:");
        bg.add(txtCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 80, 20));

        txtCategoria1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCategoria1.setForeground(new java.awt.Color(102, 102, 102));
        txtCategoria1.setText("Luciana la mejor");
        bg.add(txtCategoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 130, 20));

        txtCif1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCif1.setForeground(new java.awt.Color(102, 102, 102));
        txtCif1.setText("12345678A");
        bg.add(txtCif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 110, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Datos del Restaurante");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 20));

        txtNombre2.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre2.setText("Nombre:");
        bg.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 60, 20));

        txtNombre3.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtNombre3.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre3.setText("Luciana la mejor");
        bg.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 20));

        txtCif.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCif.setForeground(new java.awt.Color(0, 0, 0));
        txtCif.setText("CIF:");
        bg.add(txtCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 30, 20));

        jScrollPane1.setBackground(new java.awt.Color(187, 187, 187));

        jListMenus.setBackground(new java.awt.Color(204, 218, 234));
        jListMenus.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jListMenus.setForeground(new java.awt.Color(51, 51, 51));
        jListMenus.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListMenus);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 260, 130));

        jCatering.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jCatering.setForeground(new java.awt.Color(0, 0, 0));
        jCatering.setText("Catering");
        bg.add(jCatering, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 140, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Lista de Menús");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 170, 20));

        jComida.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        jComida.setForeground(new java.awt.Color(0, 0, 0));
        jComida.setText("Comida a Proporcionar:");
        bg.add(jComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        txtCamareros.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCamareros.setForeground(new java.awt.Color(102, 102, 102));
        txtCamareros.setText("Si");
        bg.add(txtCamareros, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 30, -1));

        jCamareros.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        jCamareros.setForeground(new java.awt.Color(0, 0, 0));
        jCamareros.setText("Camareros:");
        bg.add(jCamareros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jEspacio.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        jEspacio.setForeground(new java.awt.Color(0, 0, 0));
        jEspacio.setText("Espacio:");
        bg.add(jEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, -1, -1));

        jCocineros.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        jCocineros.setForeground(new java.awt.Color(0, 0, 0));
        jCocineros.setText("Cocineros:");
        bg.add(jCocineros, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        txtComida.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtComida.setForeground(new java.awt.Color(102, 102, 102));
        txtComida.setText("Filete de cerod con patats");
        bg.add(txtComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 290, -1));

        txtCocineros.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCocineros.setForeground(new java.awt.Color(102, 102, 102));
        txtCocineros.setText("No");
        bg.add(txtCocineros, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 20, -1));

        txtEspacio.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtEspacio.setForeground(new java.awt.Color(102, 102, 102));
        txtEspacio.setText("Si");
        bg.add(txtEspacio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 20, -1));

        jDecoracion.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        jDecoracion.setForeground(new java.awt.Color(0, 0, 0));
        jDecoracion.setText("Decoración:");
        bg.add(jDecoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        txtDecoracion.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtDecoracion.setForeground(new java.awt.Color(102, 102, 102));
        txtDecoracion.setText("No");
        bg.add(txtDecoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 30, -1));

        txtCodPostal.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCodPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal.setText("Código Postal:");
        bg.add(txtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 20));

        txtNum.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtNum.setForeground(new java.awt.Color(0, 0, 0));
        txtNum.setText("Nº:");
        bg.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 20));

        txtCalle.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle:");
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, 20));

        txtCalle1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCalle1.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle1.setText("LA CALLE ES EL PURO CIELO");
        bg.add(txtCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 260, 20));

        txtCodPostal1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCodPostal1.setForeground(new java.awt.Color(102, 102, 102));
        txtCodPostal1.setText("12345");
        bg.add(txtCodPostal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 20));

        txtCiudad.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad:");
        bg.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        txtCiudad1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtCiudad1.setForeground(new java.awt.Color(102, 102, 102));
        txtCiudad1.setText("Alcala de henares nojoda");
        bg.add(txtCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 220, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dirección del Restaurante");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 20));

        txtNum1.setFont(new java.awt.Font("Roboto Condensed", 0, 16)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(102, 102, 102));
        txtNum1.setText("123456789");
        bg.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 90, 20));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jRestaurante.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jRestaurante.setForeground(new java.awt.Color(51, 51, 51));
        jRestaurante.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jRestaurante.setText("Restaurante 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jRestaurante)
                .addContainerGap(446, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRestaurante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(51, 51, 51))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 690, 60));

        jLabel8.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Lista de Comidas");
        bg.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 170, 20));

        jScrollPane2.setBackground(new java.awt.Color(187, 187, 187));

        jListComidas.setBackground(new java.awt.Color(204, 218, 234));
        jListComidas.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jListComidas.setForeground(new java.awt.Color(51, 51, 51));
        jListComidas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListComidas);

        bg.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 260, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarLista(ArrayList<Comida> comidas, ArrayList<Menu> menus) {
        
        //Comidas
        ArrayList<String> lineasVenta = new ArrayList<>();
        for (Comida comida : comidas) {
            lineasVenta.add(comida.getTitulo() + " (" + comida.getId() + ") " + comida.getPrecioVenta() + "€");
        }
        DefaultListModel<String> model = new DefaultListModel<String>();
        model.addAll(lineasVenta);
        jListComidas.setModel(model);
        jListComidas.revalidate();
        jListComidas.repaint();

        //Menus
        ArrayList<String> lineasVenta2 = new ArrayList<>();
        for (Menu menuTemp : menus) {
            lineasVenta2.add(menuTemp.getNombre() + " (" + menuTemp.getId() + ") " + menuTemp.getPrecio() + "€");
        }

        DefaultListModel<String> model2 = new DefaultListModel<String>();
        model2.addAll(lineasVenta2);
        jListMenus.setModel(model2);
        jListMenus.revalidate();
        jListMenus.repaint();
    }

    public void actualizarDatos(Restaurante restaurante) {

        //Datos Empresa
        txtNombre3.setText(restaurante.getNombre());
        txtCategoria1.setText(restaurante.getEspecialidad());
        txtCif1.setText(restaurante.getCif());

        //Dirección
        Direccion direccion = restaurante.getDireccion();
        txtCalle1.setText(direccion.getCalle());
        txtCodPostal1.setText(direccion.getCodigoPostal());
        txtNum1.setText(direccion.getNumero());
        txtCiudad1.setText(direccion.getCiudad());

        //Catering
        if (restaurante.isOfreceCatering()) {
            jCatering.setText("Catering");
            txtCamareros.setText(restaurante.getCatering().isCamareros() ? "Si" : "No");
            txtDecoracion.setText(restaurante.getCatering().isDecoracion() ? "Si" : "No");
            txtEspacio.setText(restaurante.getCatering().isEspacioPrivado() ? "Si" : "No");
            txtCocineros.setText(restaurante.getCatering().isCocineros() ? "Si" : "No");
            txtComida.setText(restaurante.getCatering().getComidaAProporcionar() + " - " + restaurante.getCatering().getPrecioComida() + "€");
        } else {
            jCatering.setText("Catering: No");
            txtCamareros.setText("");
            txtDecoracion.setText("");
            txtEspacio.setText("");
            txtCocineros.setText("");
            jCamareros.setText("");
            jDecoracion.setText("");
            jEspacio.setText("");
            jCocineros.setText("");
            txtComida.setText("");
            jComida.setText("");
        }

        //Panel Top
        jRestaurante.setText("Restaurante " + restaurante.getId());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jCamareros;
    private javax.swing.JLabel jCatering;
    private javax.swing.JLabel jCocineros;
    private javax.swing.JLabel jComida;
    private javax.swing.JLabel jDecoracion;
    private javax.swing.JLabel jEspacio;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jListComidas;
    private javax.swing.JList<String> jListMenus;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jRestaurante;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCalle1;
    private javax.swing.JLabel txtCamareros;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JLabel txtCategoria1;
    private javax.swing.JLabel txtCif;
    private javax.swing.JLabel txtCif1;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCiudad1;
    private javax.swing.JLabel txtCocineros;
    private javax.swing.JLabel txtCodPostal;
    private javax.swing.JLabel txtCodPostal1;
    private javax.swing.JLabel txtComida;
    private javax.swing.JLabel txtDecoracion;
    private javax.swing.JLabel txtEspacio;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    private javax.swing.JLabel txtNum;
    private javax.swing.JLabel txtNum1;
    // End of variables declaration//GEN-END:variables
}
