/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.Catering;
import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Comida;
import com.clases.Direccion;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Menu;
import com.clases.Restaurante;
import com.clases.Venta;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


public class ContenidoVenta extends javax.swing.JPanel {

    /**
     * Creates new form contenidoVenta
     * @param consultaVentas
     */
    public ContenidoVenta(ConsultaVentas consultaVentas) {
        initComponents();
        Venta ventaActual = consultaVentas.getVentaActual();
        actualizarVenta(ventaActual);
        actualizarDatos(ventaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jVenta = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JLabel();
        txtCifDni1 = new javax.swing.JLabel();
        txtCifDni = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtId1 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombreRestaurante = new javax.swing.JLabel();
        txtNombreRestaurante1 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JLabel();
        txtNum = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtCalle1 = new javax.swing.JLabel();
        txtCodPostal1 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtCiudad1 = new javax.swing.JLabel();
        txtNum3 = new javax.swing.JLabel();
        txtCodPostal2 = new javax.swing.JLabel();
        txtNum2 = new javax.swing.JLabel();
        txtCalle2 = new javax.swing.JLabel();
        txtCalle3 = new javax.swing.JLabel();
        txtCodPostal3 = new javax.swing.JLabel();
        txtCiudad2 = new javax.swing.JLabel();
        txtCiudad3 = new javax.swing.JLabel();
        txtCif = new javax.swing.JLabel();
        txtCif1 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jTotal.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jTotal.setForeground(new java.awt.Color(51, 51, 51));
        jTotal.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jTotal.setText("9999.99$");

        jSeparator1.setBackground(new java.awt.Color(255, 153, 102));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jVenta.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jVenta.setForeground(new java.awt.Color(51, 51, 51));
        jVenta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jVenta.setText("Venta 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 690, 60));

        jScrollPane1.setBackground(new java.awt.Color(187, 187, 187));

        jList.setBackground(new java.awt.Color(204, 218, 234));
        jList.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jList.setForeground(new java.awt.Color(51, 51, 51));
        jList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 310));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        bg.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 20, 330));

        jLabel2.setFont(new java.awt.Font("Roboto Condensed Light", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Resumen del Restaurante");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 190, 20));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed Light", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Resumen de la Venta");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 170, -1));

        txtNombre.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre.setText("Nombre:");
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 60, -1));

        txtNombre1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNombre1.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre1.setText("Luciana la mejor");
        bg.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 240, -1));

        txtCifDni1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCifDni1.setForeground(new java.awt.Color(102, 102, 102));
        txtCifDni1.setText("12345678A");
        bg.add(txtCifDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, -1));

        txtCifDni.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCifDni.setForeground(new java.awt.Color(0, 0, 0));
        txtCifDni.setText("DNI/NIE:");
        bg.add(txtCifDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 60, -1));

        txtCorreo1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCorreo1.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo1.setText("eeeeeeeeeeee@eeeeeeeeeeeeeeeeeeeeeee");
        bg.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 260, -1));

        txtCorreo.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo:");
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        txtTelefono1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtTelefono1.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono1.setText("123456789");
        bg.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, 80, -1));

        txtTelefono.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Telefono:");
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        txtId1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtId1.setForeground(new java.awt.Color(102, 102, 102));
        txtId1.setText("1");
        bg.add(txtId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 30, -1));

        txtId.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtId.setForeground(new java.awt.Color(0, 0, 0));
        txtId.setText("Identificador Cliente:");
        bg.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Resumen del comprador");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 180, -1));

        txtNombreRestaurante.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNombreRestaurante.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreRestaurante.setText("Nombre:");
        bg.add(txtNombreRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        txtNombreRestaurante1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNombreRestaurante1.setForeground(new java.awt.Color(102, 102, 102));
        txtNombreRestaurante1.setText("el VIPS JODER QUIERO IR AL VIPPPS");
        bg.add(txtNombreRestaurante1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 250, -1));

        txtNum1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(102, 102, 102));
        txtNum1.setText("123456789");
        bg.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 80, -1));

        txtCodPostal.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCodPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal.setText("Código Postal:");
        bg.add(txtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        txtNum.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNum.setForeground(new java.awt.Color(0, 0, 0));
        txtNum.setText("Nº:");
        bg.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, -1, -1));

        txtCalle.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle:");
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 40, -1));

        txtCalle1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCalle1.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle1.setText("LA CALLE ES EL PURO CIELO");
        bg.add(txtCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 190, -1));

        txtCodPostal1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCodPostal1.setForeground(new java.awt.Color(102, 102, 102));
        txtCodPostal1.setText("12345");
        bg.add(txtCodPostal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 40, -1));

        txtCiudad.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad:");
        bg.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        txtCiudad1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCiudad1.setForeground(new java.awt.Color(102, 102, 102));
        txtCiudad1.setText("Alcala de henares nojoda");
        bg.add(txtCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 260, -1));

        txtNum3.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNum3.setForeground(new java.awt.Color(102, 102, 102));
        txtNum3.setText("123456789");
        bg.add(txtNum3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 80, -1));

        txtCodPostal2.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCodPostal2.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal2.setText("Código Postal:");
        bg.add(txtCodPostal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));

        txtNum2.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtNum2.setForeground(new java.awt.Color(0, 0, 0));
        txtNum2.setText("Nº:");
        bg.add(txtNum2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, -1, -1));

        txtCalle2.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCalle2.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle2.setText("Calle:");
        bg.add(txtCalle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, -1));

        txtCalle3.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCalle3.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle3.setText("alle mi casa obvio bb jejejejjejj");
        bg.add(txtCalle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 180, -1));

        txtCodPostal3.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCodPostal3.setForeground(new java.awt.Color(102, 102, 102));
        txtCodPostal3.setText("12345");
        bg.add(txtCodPostal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 40, -1));

        txtCiudad2.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCiudad2.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad2.setText("Ciudad:");
        bg.add(txtCiudad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        txtCiudad3.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCiudad3.setForeground(new java.awt.Color(102, 102, 102));
        txtCiudad3.setText("Alcala de henares nojoda");
        bg.add(txtCiudad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 150, -1));

        txtCif.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCif.setForeground(new java.awt.Color(0, 0, 0));
        txtCif.setText("CIF:");
        bg.add(txtCif, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        txtCif1.setFont(new java.awt.Font("Roboto Condensed", 0, 15)); // NOI18N
        txtCif1.setForeground(new java.awt.Color(102, 102, 102));
        txtCif1.setText("Y77777777");
        bg.add(txtCif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 70, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actualizarVenta(Venta ventaActual) {
        //Actualizar el listado de productos
        ArrayList<String> lineasVenta = new ArrayList<>();
        
        System.out.println("-------------------");
        System.out.println(ventaActual.getComidasCompradas().size());
        System.out.println(ventaActual.getMenusComprados().size());
        System.out.println(ventaActual.getCateringComprados().size());
        
        for (Comida comidaTemp : ventaActual.getComidasCompradas()) {
            lineasVenta.add(comidaTemp.getTitulo() + " (" + comidaTemp.getId() + ") " + comidaTemp.getPrecioVenta() + "€" + " x" + comidaTemp.getCantidad());
        }
        for (Menu menuTemp : ventaActual.getMenusComprados()) {
            lineasVenta.add(menuTemp.getNombre() + " (" + menuTemp.getId() + ") " + menuTemp.getPrecio() + "€" + " x" + menuTemp.getCantidad());
        }
        for(String servicioTemp : ventaActual.getCateringComprados()) {
            lineasVenta.add( "Catering" + " - " + servicioTemp + " - " + ventaActual.getRestaurante().getCatering().getPrecioServicios(servicioTemp) + "€");
        }
//        if (!(venta.getCatering() == null)) {
//            lineasVenta.add("CATERING" + " - " + venta.getCatering().getPrecioTotal() + "€");
//        }
        DefaultListModel<String> model = new DefaultListModel<String>();
        model.addAll(lineasVenta);
        jList.setModel(model);
        jList.revalidate();
        jList.repaint();
    }

    public void actualizarDatos(Venta venta) {
        Cliente cliente = venta.getCliente();
        if (cliente instanceof ClienteParticular) {
            txtCifDni1.setText(((ClienteParticular) cliente).getDni());
        } else {
            txtCifDni.setText("CIF:");
            txtCifDni1.setText(((Empresa) cliente).getCif());
        }
        //Datos Empresa
        txtNombre1.setText(cliente.getNombre());
        txtCorreo1.setText(cliente.getCorreo());
        txtTelefono1.setText(cliente.getTelefono());

        //Dirección
        Direccion direccion = cliente.getDireccion();
        txtCalle1.setText(direccion.getCalle());
        txtCodPostal1.setText(direccion.getCodigoPostal());
        txtNum1.setText(direccion.getNumero());
        txtCiudad1.setText(direccion.getCiudad());

        Restaurante restaurante = venta.getRestaurante();
        //Datos
        txtNombreRestaurante1.setText(restaurante.getNombre());
        txtCif1.setText(restaurante.getCif());
        Direccion direccionRest = restaurante.getDireccion();
        txtCalle3.setText(direccionRest.getCalle());
        txtNum3.setText(direccionRest.getNumero());
        txtCodPostal3.setText(direccionRest.getCodigoPostal());
        txtCiudad3.setText(direccionRest.getCiudad());

        //Panel Top
        jVenta.setText("Venta " + venta.getId());
        jTotal.setText(venta.getPrecioCompra() + "€");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jTotal;
    private javax.swing.JLabel jVenta;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCalle1;
    private javax.swing.JLabel txtCalle2;
    private javax.swing.JLabel txtCalle3;
    private javax.swing.JLabel txtCif;
    private javax.swing.JLabel txtCif1;
    private javax.swing.JLabel txtCifDni;
    private javax.swing.JLabel txtCifDni1;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCiudad1;
    private javax.swing.JLabel txtCiudad2;
    private javax.swing.JLabel txtCiudad3;
    private javax.swing.JLabel txtCodPostal;
    private javax.swing.JLabel txtCodPostal1;
    private javax.swing.JLabel txtCodPostal2;
    private javax.swing.JLabel txtCodPostal3;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtCorreo1;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtId1;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtNombre1;
    private javax.swing.JLabel txtNombreRestaurante;
    private javax.swing.JLabel txtNombreRestaurante1;
    private javax.swing.JLabel txtNum;
    private javax.swing.JLabel txtNum1;
    private javax.swing.JLabel txtNum2;
    private javax.swing.JLabel txtNum3;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
