/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.Catering;
import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Direccion;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Restaurante;
import com.clases.Venta;
import java.util.ArrayList;
import javax.swing.DefaultListModel;


 
public class ContenidoUsuario extends javax.swing.JPanel {

    /**
     * Creates new form contenidoVenta
     */
    public ContenidoUsuario(Cliente cliente) {
        initComponents();
        actualizarDatos(cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jCliente = new javax.swing.JLabel();
        txtWebApellido = new javax.swing.JLabel();
        txtWebApellido1 = new javax.swing.JLabel();
        txtCifDni1 = new javax.swing.JLabel();
        txtCifDni = new javax.swing.JLabel();
        txtCorreo1 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNum1 = new javax.swing.JLabel();
        txtCodPostal = new javax.swing.JLabel();
        txtNum = new javax.swing.JLabel();
        txtCalle = new javax.swing.JLabel();
        txtCalle1 = new javax.swing.JLabel();
        txtCodPostal1 = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JLabel();
        txtCiudad1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JLabel();
        txtNombre3 = new javax.swing.JLabel();
        txtCifDni2 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        jCliente.setFont(new java.awt.Font("Roboto Condensed Light", 0, 36)); // NOI18N
        jCliente.setForeground(new java.awt.Color(51, 51, 51));
        jCliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCliente.setText("Cliente 1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jCliente)
                .addContainerGap(494, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 690, 60));

        txtWebApellido.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtWebApellido.setForeground(new java.awt.Color(0, 0, 0));
        txtWebApellido.setText("Apellido:");
        bg.add(txtWebApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 70, 20));

        txtWebApellido1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtWebApellido1.setForeground(new java.awt.Color(102, 102, 102));
        txtWebApellido1.setText("Luciana la mejor");
        bg.add(txtWebApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 250, 20));

        txtCifDni1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCifDni1.setForeground(new java.awt.Color(102, 102, 102));
        txtCifDni1.setText("12345678A");
        bg.add(txtCifDni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 110, 20));

        txtCifDni.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCifDni.setForeground(new java.awt.Color(0, 0, 0));
        txtCifDni.setText("DNI/NIE:");
        bg.add(txtCifDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 70, 20));

        txtCorreo1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCorreo1.setForeground(new java.awt.Color(102, 102, 102));
        txtCorreo1.setText("eeeeeeeeeeee@eeeeeeeeeeeeeeeeeeeeeee");
        bg.add(txtCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 300, 20));

        txtCorreo.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCorreo.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreo.setText("Correo:");
        bg.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, 20));

        txtTelefono1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtTelefono1.setForeground(new java.awt.Color(102, 102, 102));
        txtTelefono1.setText("123456789");
        bg.add(txtTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, 20));

        txtTelefono.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefono.setText("Telefono:");
        bg.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed Light", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Dirección del Usuario");
        bg.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 180, 20));

        txtNum1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNum1.setForeground(new java.awt.Color(102, 102, 102));
        txtNum1.setText("123456789");
        bg.add(txtNum1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 90, 20));

        txtCodPostal.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCodPostal.setForeground(new java.awt.Color(0, 0, 0));
        txtCodPostal.setText("Código Postal:");
        bg.add(txtCodPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, 20));

        txtNum.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNum.setForeground(new java.awt.Color(0, 0, 0));
        txtNum.setText("Nº:");
        bg.add(txtNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, 20));

        txtCalle.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCalle.setForeground(new java.awt.Color(0, 0, 0));
        txtCalle.setText("Calle:");
        bg.add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 40, 20));

        txtCalle1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCalle1.setForeground(new java.awt.Color(102, 102, 102));
        txtCalle1.setText("LA CALLE ES EL PURO CIELO");
        bg.add(txtCalle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 280, 20));

        txtCodPostal1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCodPostal1.setForeground(new java.awt.Color(102, 102, 102));
        txtCodPostal1.setText("12345");
        bg.add(txtCodPostal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 50, 20));

        txtCiudad.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCiudad.setForeground(new java.awt.Color(0, 0, 0));
        txtCiudad.setText("Ciudad:");
        bg.add(txtCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 60, 20));

        txtCiudad1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCiudad1.setForeground(new java.awt.Color(102, 102, 102));
        txtCiudad1.setText("Alcala de henares nojoda");
        bg.add(txtCiudad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 190, 20));

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Datos del Usuario");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 180, 20));

        txtNombre2.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNombre2.setForeground(new java.awt.Color(0, 0, 0));
        txtNombre2.setText("Nombre:");
        bg.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 60, 20));

        txtNombre3.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtNombre3.setForeground(new java.awt.Color(102, 102, 102));
        txtNombre3.setText("Luciana la mejor");
        bg.add(txtNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 250, 20));

        txtCifDni2.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtCifDni2.setForeground(new java.awt.Color(0, 0, 0));
        txtCifDni2.setText("CIF:");
        bg.add(txtCifDni2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 40, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void actualizarDatos(Cliente cliente){
        if(cliente instanceof ClienteParticular){
            txtCifDni1.setText(((ClienteParticular) cliente).getDni());
            txtCifDni2.setText("");
            txtCifDni.setText("DNI/NIE:");
            txtWebApellido.setText("Apellido:");
            txtWebApellido1.setText(((ClienteParticular) cliente).getApellido());

        }else{
            txtCifDni.setText("");
            txtCifDni2.setText("CIF:");
            txtCifDni1.setText(((Empresa) cliente).getCif());
            txtWebApellido.setText("Web:");
            txtWebApellido1.setText(((Empresa) cliente).getWeb());
        }
        //Datos Empresa
        txtNombre3.setText(cliente.getNombre());
        txtCorreo1.setText(cliente.getCorreo());
        txtTelefono1.setText(cliente.getTelefono());

        //Dirección
        Direccion direccion = cliente.getDireccion();
        txtCalle1.setText(direccion.getCalle());
        txtCodPostal1.setText(direccion.getCodigoPostal());
        txtNum1.setText(direccion.getNumero());
        txtCiudad1.setText(direccion.getCiudad());
        
        //Panel Top
        jCliente.setText("Cliente " + cliente.getId());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jCliente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCalle;
    private javax.swing.JLabel txtCalle1;
    private javax.swing.JLabel txtCifDni;
    private javax.swing.JLabel txtCifDni1;
    private javax.swing.JLabel txtCifDni2;
    private javax.swing.JLabel txtCiudad;
    private javax.swing.JLabel txtCiudad1;
    private javax.swing.JLabel txtCodPostal;
    private javax.swing.JLabel txtCodPostal1;
    private javax.swing.JLabel txtCorreo;
    private javax.swing.JLabel txtCorreo1;
    private javax.swing.JLabel txtNombre2;
    private javax.swing.JLabel txtNombre3;
    private javax.swing.JLabel txtNum;
    private javax.swing.JLabel txtNum1;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtTelefono1;
    private javax.swing.JLabel txtWebApellido;
    private javax.swing.JLabel txtWebApellido1;
    // End of variables declaration//GEN-END:variables
}
