/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.interfaz.*;
import com.clases.MainManager;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    
    int xMouse,yMouse;
    
    /**
     * Creates new form Login
     */
    public Login() {
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */

    try {
        javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (Exception e) {
        System.err.println("Failed to initialize LaF");

        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            System.out.println(info.getName());
            if ("Flatlaf".equals(info.getName())) {
            System.out.println("Flatlaf look and feel stablished");
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
            }
        }
        } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    //</editor-fold> //Establece el Flat-Laf look and feel (Dependencia)
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        flecha = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        paneltop = new javax.swing.JPanel();
        moto = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JLabel();
        correofield = new javax.swing.JTextField();
        pswfield = new javax.swing.JPasswordField();
        registxt = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        sep2 = new javax.swing.JSeparator();
        txtpsw1 = new javax.swing.JLabel();
        cuentatxt = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flecha.setBackground(new java.awt.Color(255, 153, 0));
        flecha.setForeground(new java.awt.Color(153, 153, 0));
        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flecha (2).png"))); // NOI18N
        flecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                flechaMouseEntered(evt);
            }
        });
        bg.add(flecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, -1, -1));

        header.setBackground(new java.awt.Color(255, 153, 102));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(255, 153, 102));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        paneltop.setBackground(new java.awt.Color(255, 153, 102));

        moto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/moto1.png"))); // NOI18N

        javax.swing.GroupLayout paneltopLayout = new javax.swing.GroupLayout(paneltop);
        paneltop.setLayout(paneltopLayout);
        paneltopLayout.setHorizontalGroup(
            paneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltopLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(moto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paneltopLayout.setVerticalGroup(
            paneltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneltopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(moto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(paneltop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 280));

        txtcorreo.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(51, 51, 51));
        txtcorreo.setText("CORREO");
        bg.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        correofield.setBackground(new java.awt.Color(255, 255, 255));
        correofield.setForeground(new java.awt.Color(204, 204, 204));
        correofield.setText("Ingrese el correo de usuario");
        correofield.setBorder(null);
        correofield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                correofieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                correofieldFocusLost(evt);
            }
        });
        correofield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correofieldMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                correofieldMousePressed(evt);
            }
        });
        correofield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correofieldActionPerformed(evt);
            }
        });
        bg.add(correofield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 260, -1));

        pswfield.setBackground(new java.awt.Color(255, 255, 255));
        pswfield.setForeground(new java.awt.Color(204, 204, 204));
        pswfield.setText("********");
        pswfield.setBorder(null);
        pswfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pswfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pswfieldFocusLost(evt);
            }
        });
        pswfield.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pswfieldMousePressed(evt);
            }
        });
        bg.add(pswfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 260, -1));

        registxt.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        registxt.setForeground(new java.awt.Color(255, 135, 83));
        registxt.setText("Registrarme");
        registxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registxtMouseExited(evt);
            }
        });
        bg.add(registxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 90, -1));
        bg.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 270, 10));
        bg.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 270, 10));

        txtpsw1.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        txtpsw1.setForeground(new java.awt.Color(51, 51, 51));
        txtpsw1.setText("CONTRASEÑA");
        bg.add(txtpsw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        cuentatxt.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        cuentatxt.setForeground(new java.awt.Color(51, 51, 51));
        cuentatxt.setText("¿No tienes cuenta?");
        bg.add(cuentatxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 150, -1));

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        javaeatlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo.png"))); // NOI18N
        bg.add(javaeatlogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 330, 400, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 400, 600);
    }// </editor-fold>//GEN-END:initComponents
    
    private void correofieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correofieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correofieldActionPerformed

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void correofieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correofieldMouseClicked
        
    }//GEN-LAST:event_correofieldMouseClicked

    private void correofieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correofieldMousePressed
        
    }//GEN-LAST:event_correofieldMousePressed

    private void pswfieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pswfieldMousePressed
    }//GEN-LAST:event_pswfieldMousePressed

    private void flechaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaMouseEntered
        
    }//GEN-LAST:event_flechaMouseEntered

    private void flechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaMouseClicked
        
        String correo = correofield.getText();
        String clave = String.valueOf(pswfield.getPassword());
        if(correo.equals("Ingrese el correo de usuario") || correo.equals("")){
            JOptionPane.showMessageDialog(this, "Introduzca un correo","Datos incorrectos",JOptionPane.ERROR_MESSAGE);

        } else if (clave.equals("********") || clave.equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca una contraseña","Datos incorrectos",JOptionPane.ERROR_MESSAGE);

        } else{
            String mensaje = MainManager.verificaLogin(correo, clave);
            if(!mensaje.equals("")){
                JOptionPane.showMessageDialog(this, mensaje, "Datos incorrectos", JOptionPane.ERROR_MESSAGE);
                pswfield.setText("");
            } 
            
        }
             
        
    }//GEN-LAST:event_flechaMouseClicked

    private void registxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registxtMouseEntered
        registxt.setForeground(new Color(255,102,0));
    }//GEN-LAST:event_registxtMouseEntered

    private void registxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registxtMouseExited
        
        registxt.setForeground(new Color(255,135,83));
    }//GEN-LAST:event_registxtMouseExited

    private void registxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registxtMouseClicked
        MainManager.showFrame("RegistroCliente");
    }//GEN-LAST:event_registxtMouseClicked

    private void correofieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correofieldFocusGained
        if(correofield.getText().equals("Ingrese el correo de usuario")){
            correofield.setText("");
            correofield.setForeground(Color.black);
        }
    }//GEN-LAST:event_correofieldFocusGained

    private void correofieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correofieldFocusLost
        if(correofield.getText().isEmpty()){
            correofield.setText("Ingrese el correo de usuario");
            correofield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_correofieldFocusLost

    private void pswfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfieldFocusGained
        String clave = String.valueOf(pswfield.getPassword());
        if(clave.equals("********") || clave.equals("")){
            pswfield.setText("");
            pswfield.setForeground(Color.black);
        }
    }//GEN-LAST:event_pswfieldFocusGained

    private void pswfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pswfieldFocusLost
        if(String.valueOf(pswfield.getPassword()).isEmpty()){
            pswfield.setText("********");
            pswfield.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_pswfieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JTextField correofield;
    private javax.swing.JLabel cuentatxt;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLabel flecha;
    private javax.swing.JPanel header;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JLabel moto;
    private javax.swing.JPanel paneltop;
    private javax.swing.JPasswordField pswfield;
    private javax.swing.JLabel registxt;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JLabel txtcorreo;
    private javax.swing.JLabel txtexit;
    private javax.swing.JLabel txtpsw1;
    // End of variables declaration//GEN-END:variables
}
