/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.clases.Cliente;
import com.clases.ClienteParticular;
import com.clases.Empresa;
import com.clases.MainManager;
import com.clases.Restaurante;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Point;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.border.LineBorder;


public class MenuPrincipal extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private ArrayList<TemplateRestaurante> listaTemplates;
    private ArrayList<Restaurante> restaurantes;
    private String especialidad = "Todas";
    private boolean filtroCatering;
    private Cliente clienteActual;
    private boolean clienteParticular;
    private String textoBuscador = "";

    /*
	tipoOrden indica el tipo de orden que se usa:
	 0 -> Por relevancia
         1 -> Por tiempo
	 2 -> Por gatos de envío
         
     */
    int tipoOrden;

    /**
     * Creates new form MainMenu
     */
    public MenuPrincipal() {

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
            System.err.println("Failed to initialize LaF");

            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    System.out.println(info.getName());
                    if ("Flatlaf".equals(info.getName())) {
                        System.out.println("Flatlaf look and feel stablished");
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
        //</editor-fold> //Establece el Flat-Laf look and feel (Dependencia)
        initComponents();
        this.setLocationRelativeTo(null);
        this.restaurantes = MainManager.getRestaurantes();
        tipoOrden = 0;
        filtroCatering = false;
        clienteActual = MainManager.getClienteIniciado();
        listaTemplates = new ArrayList<>();
        jTextBienvenido.setText("Bienvenido/a " + MainManager.getClienteIniciado().getNombre() + "..." + "¿Que te apetece comer hoy?");
        if (clienteActual instanceof ClienteParticular) {
            jCatering.setVisible(false);
            clienteParticular = true;
        }
        showRestaurants();
        



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        javaeatlogo = new javax.swing.JLabel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        jBuscador = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jCuenta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        topPanel = new javax.swing.JPanel();
        jTextBienvenido = new javax.swing.JLabel();
        jCatering = new javax.swing.JCheckBox();
        jEspecialidad = new javax.swing.JComboBox<>();
        jOrden = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Scroll = new javax.swing.JScrollPane();
        PanelParent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(241, 241, 241));
        header.setPreferredSize(new java.awt.Dimension(1250, 60));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javaeatlogo.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo2.png"))); // NOI18N
        header.add(javaeatlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, 70));

        exitpanel.setBackground(new java.awt.Color(241, 241, 241));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        header.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 60, 70));

        jBuscador.setBackground(new java.awt.Color(204, 204, 204));
        jBuscador.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        jBuscador.setForeground(new java.awt.Color(102, 102, 102));
        jBuscador.setText("Comida...");
        jBuscador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jBuscadorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBuscadorFocusLost(evt);
            }
        });
        jBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscadorActionPerformed(evt);
            }
        });
        header.add(jBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 541, 30));

        jButton2.setBackground(new java.awt.Color(164, 204, 222));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        header.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, 30));

        jCuenta.setBackground(new java.awt.Color(164, 204, 222));
        jCuenta.setForeground(new java.awt.Color(0, 0, 0));
        jCuenta.setText("Cuenta");
        jCuenta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCuentaActionPerformed(evt);
            }
        });
        header.add(jCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1064, 20, 120, 30));

        jButton1.setBackground(new java.awt.Color(238, 88, 88));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 30, 30));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 70));

        topPanel.setBackground(new java.awt.Color(238, 88, 88));
        topPanel.setMaximumSize(new java.awt.Dimension(1250, 200));
        topPanel.setPreferredSize(new java.awt.Dimension(1248, 200));

        jTextBienvenido.setFont(new java.awt.Font("Roboto Condensed Light", 2, 24)); // NOI18N
        jTextBienvenido.setForeground(new java.awt.Color(0, 0, 0));
        jTextBienvenido.setText("Bienvenido/a, @Nombre ¿Que te apetece comer hoy?");

        jCatering.setFont(new java.awt.Font("Roboto Slab Medium", 0, 13)); // NOI18N
        jCatering.setForeground(new java.awt.Color(0, 0, 0));
        jCatering.setText("Dispone de Catering");
        jCatering.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCateringActionPerformed(evt);
            }
        });

        jEspecialidad.setBackground(new java.awt.Color(255, 255, 255));
        jEspecialidad.setForeground(new java.awt.Color(51, 51, 51));
        jEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Internacional", "Mediterránea", "Sushi", "Comida India", "Comida Callejera", "Vegetariana", "Vegana", "Pollo frito" }));
        jEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEspecialidadActionPerformed(evt);
            }
        });

        jOrden.setBackground(new java.awt.Color(255, 255, 255));
        jOrden.setForeground(new java.awt.Color(51, 51, 51));
        jOrden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Relevancia", "Tiempo medio de envío", "Gastos de envío" }));
        jOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOrdenActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Especialidad");

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ordenar restaurantes");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jTextBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jCatering)
                .addGap(18, 18, 18)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(38, 38, 38))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCatering)
                    .addComponent(jTextBienvenido))
                .addGap(22, 22, 22))
        );

        bg.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1250, 100));

        Scroll.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        Scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        Scroll.setColumnHeaderView(null);

        PanelParent.setBackground(new java.awt.Color(255, 255, 255));
        PanelParent.setLayout(new javax.swing.BoxLayout(PanelParent, javax.swing.BoxLayout.Y_AXIS));
        Scroll.setViewportView(PanelParent);

        bg.add(Scroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1250, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 1250, 650);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private boolean nearEnough(Restaurante rest, Cliente cliente) {
        String cpRestaurante = rest.getDireccion().getCodigoPostal().substring(0, 4);
        String cpCliente = cliente.getDireccion().getCodigoPostal().substring(0, 4);
        return cpRestaurante.equals(cpCliente);
    }

    private ArrayList<Restaurante> ordenarYFiltrarRestaurantes() {
        ArrayList<Restaurante> restaurantesEspecialidad = new ArrayList<>();
        ArrayList<Restaurante> restaurantesCercanos = new ArrayList<>();
        ArrayList<Restaurante> restaurantesOrdenados = new ArrayList<>();
        for (Restaurante rest : restaurantes) {
            if (nearEnough(rest, clienteActual)) {

                restaurantesCercanos.add(rest);
            }
        }

        if (!("".equals(textoBuscador) || "Comida...".equals(textoBuscador))) {
            System.out.println(textoBuscador);
            String[] palabrasClaves = textoBuscador.split(" ");
            ArrayList<Restaurante> restaurantesBuscados = new ArrayList<>();

            for (Restaurante rest : restaurantesCercanos) {
                String[] tituloRestaurante = rest.getNombre().split(" ");
                boolean contienePalabraClave = false;
                for (String palabraClave : palabrasClaves) {
                    for (String nombre : tituloRestaurante) {
                        if (palabraClave.toLowerCase().equals(nombre.toLowerCase())) {
                            contienePalabraClave = true;
                            break;
                        }
                    }
                }
                if(contienePalabraClave){
                    restaurantesBuscados.add(rest);
                }
            }
            restaurantesCercanos = restaurantesBuscados;
        }

        if (especialidad != "Todas") {
            for (Restaurante rest : restaurantesCercanos) {
                if (especialidad.equals(rest.getEspecialidad())) {

                    restaurantesEspecialidad.add(rest);
                }
            }
            restaurantesCercanos = restaurantesEspecialidad;
        }

        if (!clienteParticular && filtroCatering) {
            for (Restaurante rest : restaurantesCercanos) {
                if (rest.isOfreceCatering()) {
                    restaurantesOrdenados.add(rest);
                }
            }

        } else {
            restaurantesOrdenados = restaurantesCercanos;
        }
        for(Restaurante rest : restaurantesOrdenados){
            System.out.println(rest.getNombre());
        }
        MainManager.bubbleSort(tipoOrden, restaurantesOrdenados);
        return restaurantesOrdenados;

    }

    private void showRestaurants() {
        System.out.println("Mostrando restaurantes...");
        ArrayList<Restaurante> restaurantesOrdenados = ordenarYFiltrarRestaurantes();
        generarPaneles(restaurantesOrdenados.size());
        rellenarPaneles(restaurantesOrdenados);
         new java.util.Timer().schedule(
		    new java.util.TimerTask() {
		@Override
		public void run() {
		    Scroll.getVerticalScrollBar().setValue(0);
		}
	    },200);

    }

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.red);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        textoBuscador = jBuscador.getText();
        actualizarPanel();
        showRestaurants();


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCuentaActionPerformed
        MainManager.showFrame("Cuenta");
    }//GEN-LAST:event_jCuentaActionPerformed

    private void jBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscadorActionPerformed
        
    }//GEN-LAST:event_jBuscadorActionPerformed

    private void jBuscadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBuscadorFocusLost
        if (jBuscador.getText().equals("")) {
            jBuscador.setText("Comida...");
            jBuscador.setBackground(new Color(204,204,204));
            jBuscador.setForeground(new Color(102,102,102));

        }
    }//GEN-LAST:event_jBuscadorFocusLost

    private void jBuscadorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBuscadorFocusGained
        if(jBuscador.getText().equals("Comida...")){
            jBuscador.setText("");
            jBuscador.setBackground(Color.white);
            jBuscador.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_jBuscadorFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jBuscador.setText("Comida...");
        jBuscador.setBackground(new Color(204,204,204));
        jBuscador.setForeground(new Color(102,102,102));
        textoBuscador = jBuscador.getText();
        actualizarPanel();
        showRestaurants();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOrdenActionPerformed
        // TODO add your handling code here:
        tipoOrden = jOrden.getSelectedIndex();
        actualizarPanel();
        showRestaurants();
    }//GEN-LAST:event_jOrdenActionPerformed

    private void jEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEspecialidadActionPerformed
        // TODO add your handling code here:
        especialidad = jEspecialidad.getItemAt(jEspecialidad.getSelectedIndex());
        actualizarPanel();
        showRestaurants();
    }//GEN-LAST:event_jEspecialidadActionPerformed

    private void jCateringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCateringActionPerformed
        filtroCatering = jCatering.isSelected();
        actualizarPanel();
        showRestaurants();
    }//GEN-LAST:event_jCateringActionPerformed

    public void generarPaneles(int num) {
        System.out.println("Generando Paneles");
        int resto = num % 3;
        int numeroPaneles;
        if (resto == 0) {
            numeroPaneles = num / 3;
        } else {
            numeroPaneles = (int) num / 3 + 1;
        }
        for (int i = 0; i < numeroPaneles; i++) {
            TemplatePanels panel = new TemplatePanels();
            int n = 3;
            if (i == numeroPaneles - 1 && resto != 0) {
                n = resto;
            }
            for (int j = 0; j < n; j++) {
                TemplateRestaurante template = new TemplateRestaurante();

                panel.add(template);
                listaTemplates.add(template);
            }
            //panel.setBorder(new LineBorder(Color.red));     //Pintamos de rojo para ver lo limites
            PanelParent.add(panel);
        }
        PanelParent.revalidate();
        PanelParent.repaint();
        Scroll.repaint();
    }

    public void rellenarPaneles(ArrayList<Restaurante> listaRestaurantes) {
        System.out.println("Rellenando Paneles");
        int i = 0;
        for (TemplateRestaurante template : listaTemplates) {
            Restaurante rest = listaRestaurantes.get(i);
            template.setTitulo(rest.getNombre());
            template.setInformacion(rest.getCalificacionMedia(), rest.getEspecialidad(), rest.getGastosEnvio());
            template.setTiempo(rest.getTiempoEnvio());
            template.setProduct(rest);
            String path = rest.getNombreFotografia();
            template.setImageFromPath(path);
            //template.setBorder(new LineBorder(Color.blue)); //Pintamos de azul para ver lo limites
            i++;

        }
    }
    
    
    public void actualizarPanel() {
        PanelParent.removeAll();
        PanelParent.revalidate();
        PanelParent.repaint();
        listaTemplates.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelParent;
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JPanel header;
    private javax.swing.JTextField jBuscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCatering;
    private javax.swing.JButton jCuenta;
    private javax.swing.JComboBox<String> jEspecialidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> jOrden;
    private javax.swing.JLabel jTextBienvenido;
    private javax.swing.JLabel javaeatlogo;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
