/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.clases.MainManager;
import com.clases.Opinion;
import com.clases.Restaurante;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;


public class Opiniones extends javax.swing.JFrame {

    private int xMouse, yMouse;
    private VerRestaurante verRestaurante;
    private ArrayList<TemplateComentario> opinionTemplates = new ArrayList<>();
    private Restaurante rest;
    private ArrayList<Opinion> opiniones = new ArrayList<>();

    /**
     * Creates new form Comentar
     *
     * @param verRestaurante
     */
    public Opiniones(VerRestaurante verRestaurante) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.verRestaurante = verRestaurante;
        this.rest = verRestaurante.getRestaurante();
        opiniones = rest.getOpiniones();
        Comentario.setText("");
        actualizarOpiniones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        NewOpinion = new javax.swing.JPanel();
        Comentario = new javax.swing.JTextArea();
        Puntuacion6 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        ComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPaneOpiniones = new javax.swing.JScrollPane();
        jPanelOpiniones = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        javaeatlogo = new javax.swing.JLabel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NewOpinion.setBackground(new java.awt.Color(255, 255, 255));
        NewOpinion.setPreferredSize(new java.awt.Dimension(1054, 250));

        Comentario.setBackground(new java.awt.Color(255, 255, 255));
        Comentario.setColumns(45);
        Comentario.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        Comentario.setForeground(new java.awt.Color(51, 51, 51));
        Comentario.setLineWrap(true);
        Comentario.setRows(1);
        Comentario.setText("Buen restaurante, la comida perfecta y aún super caliente de temperatura 10/10.");
        Comentario.setWrapStyleWord(true);
        Comentario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        Comentario.setMargin(new java.awt.Insets(2, 2, 2, 6));
        Comentario.setPreferredSize(new java.awt.Dimension(947, 90));

        Puntuacion6.setFont(new java.awt.Font("Roboto Condensed Light", 0, 22)); // NOI18N
        Puntuacion6.setForeground(new java.awt.Color(238, 88, 88));
        Puntuacion6.setText("Puntuación media:");

        jTextFieldTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldTitulo.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        jTextFieldTitulo.setForeground(new java.awt.Color(51, 51, 51));

        ComboBox.setBackground(new java.awt.Color(255, 255, 255));
        ComboBox.setEditable(true);
        ComboBox.setFont(new java.awt.Font("Roboto Condensed Light", 0, 18)); // NOI18N
        ComboBox.setForeground(new java.awt.Color(238, 88, 88));
        ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        ComboBox.setSelectedIndex(2);
        ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Condensed Light", 2, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Opiniones:");

        javax.swing.GroupLayout NewOpinionLayout = new javax.swing.GroupLayout(NewOpinion);
        NewOpinion.setLayout(NewOpinionLayout);
        NewOpinionLayout.setHorizontalGroup(
            NewOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewOpinionLayout.createSequentialGroup()
                .addGroup(NewOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NewOpinionLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(NewOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTitulo)
                            .addGroup(NewOpinionLayout.createSequentialGroup()
                                .addComponent(Puntuacion6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(NewOpinionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        NewOpinionLayout.setVerticalGroup(
            NewOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NewOpinionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewOpinionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Puntuacion6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Comentario, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bg.add(NewOpinion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1050, 240));

        jScrollPaneOpiniones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneOpiniones.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanelOpiniones.setBackground(new java.awt.Color(242, 242, 242));
        jPanelOpiniones.setMaximumSize(new java.awt.Dimension(1058, 32767));
        jPanelOpiniones.setMinimumSize(new java.awt.Dimension(1058, 100));
        jPanelOpiniones.setPreferredSize(new java.awt.Dimension(1058, 700));
        jPanelOpiniones.setLayout(new javax.swing.BoxLayout(jPanelOpiniones, javax.swing.BoxLayout.Y_AXIS));
        jScrollPaneOpiniones.setViewportView(jPanelOpiniones);

        bg.add(jScrollPaneOpiniones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 1050, 270));

        header.setBackground(new java.awt.Color(241, 241, 241));
        header.setPreferredSize(new java.awt.Dimension(1250, 60));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javaeatlogo.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo2.png"))); // NOI18N
        header.add(javaeatlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 50));

        exitpanel.setBackground(new java.awt.Color(241, 241, 241));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitpanelLayout.createSequentialGroup()
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        header.add(exitpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 90, 70));

        flecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        flecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/flecha (3).png"))); // NOI18N
        flecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaMouseClicked(evt);
            }
        });
        header.add(flecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 50));

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 50));

        jLabel7.setFont(new java.awt.Font("Roboto Condensed Light", 2, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mi opinión:");
        bg.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 180, 30));

        jButton1.setBackground(new java.awt.Color(238, 88, 88));
        jButton1.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("AÑADIR OPINIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actualizarOpiniones() {
        clearOpiniones();
        generarOpiniones();
        rellenarOpiniones();

    }

    private void generarOpiniones() {
        for (Opinion opinion : opiniones) {
            TemplateComentario template = new TemplateComentario();
            opinionTemplates.add(template);
            jPanelOpiniones.add(template);

        }
        jPanelOpiniones.revalidate();
        jPanelOpiniones.repaint();
        jScrollPaneOpiniones.repaint();

    }

    private void rellenarOpiniones() {
        int i = 0;
        for (TemplateComentario template : opinionTemplates) {
            Opinion opinion = opiniones.get(i);
            template.setTitulo(opinion.getTitulo());
            template.setPuntuacion(opinion.getCalificacion());
            template.setOpinion(opinion.getComentario());
            i++;
        }
    }

    private void clearOpiniones() {
        jPanelOpiniones.removeAll();
        jPanelOpiniones.revalidate();
        jPanelOpiniones.repaint();
        opinionTemplates.clear();
    }

    private void ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxActionPerformed

    }//GEN-LAST:event_ComboBoxActionPerformed

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.red);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void flechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaMouseClicked
        this.setVisible(false);
        this.dispose();
        verRestaurante.setVisible(true);
        verRestaurante.actualizarRestaurante();
    }//GEN-LAST:event_flechaMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String titulo = jTextFieldTitulo.getText();
        int puntuacion = ComboBox.getSelectedIndex() + 1;
        String comentario = Comentario.getText();
        
        if(titulo.isEmpty() || comentario.isEmpty()){
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } 
        
        Opinion opinion = new Opinion(titulo,puntuacion,comentario);
        opiniones.add(opinion);
        jTextFieldTitulo.setText("");
        Comentario.setText("");
        
        actualizarOpiniones();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opiniones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Opiniones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox;
    private javax.swing.JTextArea Comentario;
    private javax.swing.JPanel NewOpinion;
    private javax.swing.JLabel Puntuacion6;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLabel flecha;
    private javax.swing.JPanel header;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelOpiniones;
    private javax.swing.JScrollPane jScrollPaneOpiniones;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JLabel javaeatlogo;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
