/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.clases.MainManager;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import com.clases.*;
import com.formdev.flatlaf.FlatLightLaf;


public class RegistroTarjeta extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public RegistroTarjeta() {
         //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         
For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html */

    try {
        javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (Exception e) {
        System.err.println("Failed to initialize LaF");

        try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            System.out.println(info.getName());
            if ("Flatlaf".equals(info.getName())) {
            System.out.println("Flatlaf look and feel stablished");
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
            }
        }
        } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    //</editor-fold> //Establece el Flat-Laf look and feel (Dependencia)
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void PutText(String str,JTextField textfield){
        if(textfield.getText().equals(str)){
            textfield.setText("");
            textfield.setForeground(Color.black);
        }
    }
    
    private void SetText(String str,JTextField textfield){
        if(textfield.equals("")){
            textfield.setText(str);
            textfield.setForeground(new Color(204,204,204));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitpanel = new javax.swing.JPanel();
        txtexit = new javax.swing.JLabel();
        javaeatlogo1 = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JLabel();
        flecha = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtIBAN = new javax.swing.JLabel();
        sep2 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        sep4 = new javax.swing.JSeparator();
        txtCaducidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedNumero = new javax.swing.JFormattedTextField();
        jFormattedCaducidad = new javax.swing.JFormattedTextField();
        jTextTitular = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMinimumSize(new java.awt.Dimension(400, 360));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        header.setBackground(new java.awt.Color(238, 88, 88));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitpanel.setBackground(new java.awt.Color(238, 88, 88));

        txtexit.setBackground(new java.awt.Color(0, 0, 0));
        txtexit.setFont(new java.awt.Font("Roboto Thin", 1, 24)); // NOI18N
        txtexit.setForeground(new java.awt.Color(0, 0, 0));
        txtexit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtexit.setText("X");
        txtexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtexitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtexitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtexitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitpanelLayout = new javax.swing.GroupLayout(exitpanel);
        exitpanel.setLayout(exitpanelLayout);
        exitpanelLayout.setHorizontalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exitpanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtexit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        exitpanelLayout.setVerticalGroup(
            exitpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtexit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javaeatlogo1.setFont(new java.awt.Font("Roboto Condensed", 1, 36)); // NOI18N
        javaeatlogo1.setForeground(new java.awt.Color(255, 102, 0));
        javaeatlogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/javaEatLogo2.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(javaeatlogo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javaeatlogo1))
                .addGap(0, 1, Short.MAX_VALUE))
        );

        bg.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        txtTarjeta.setFont(new java.awt.Font("Roboto Condensed", 1, 32)); // NOI18N
        txtTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        txtTarjeta.setText("Tarjeta de Crédito");
        bg.add(txtTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        flecha.setFont(new java.awt.Font("Roboto Condensed", 0, 17)); // NOI18N
        flecha.setForeground(new java.awt.Color(51, 51, 51));
        flecha.setIcon(new javax.swing.ImageIcon("C:\\Users\\lucia\\OneDrive\\Escritorio\\PL2_Diaz_22_23\\src\\main\\resources\\images\\flecha (2).png")); // NOI18N
        flecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        flecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                flechaMouseClicked(evt);
            }
        });
        bg.add(flecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 50, 40));

        txtNombre.setFont(new java.awt.Font("Roboto Condensed", 0, 17)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(51, 51, 51));
        txtNombre.setText("Nombre del titular");
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        txtIBAN.setFont(new java.awt.Font("Roboto Condensed", 0, 17)); // NOI18N
        txtIBAN.setForeground(new java.awt.Color(51, 51, 51));
        txtIBAN.setText("Número de Tarjeta");
        bg.add(txtIBAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        bg.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 270, 10));
        bg.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 270, 10));
        bg.add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 270, 10));

        txtCaducidad.setFont(new java.awt.Font("Roboto Condensed", 0, 17)); // NOI18N
        txtCaducidad.setForeground(new java.awt.Color(51, 51, 51));
        txtCaducidad.setText("Fecha de caducidad (MM/AA)");
        bg.add(txtCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/tarjeta.png"))); // NOI18N
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 70, 80));

        jFormattedNumero.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedNumero.setBorder(null);
        jFormattedNumero.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jFormattedNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedNumeroFocusLost(evt);
            }
        });
        jFormattedNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedNumeroActionPerformed(evt);
            }
        });
        bg.add(jFormattedNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 270, 20));

        jFormattedCaducidad.setBackground(new java.awt.Color(255, 255, 255));
        jFormattedCaducidad.setBorder(null);
        jFormattedCaducidad.setForeground(new java.awt.Color(51, 51, 51));
        try {
            jFormattedCaducidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedCaducidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedCaducidadFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedCaducidadFocusLost(evt);
            }
        });
        jFormattedCaducidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedCaducidadActionPerformed(evt);
            }
        });
        bg.add(jFormattedCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 270, 20));

        jTextTitular.setBackground(new java.awt.Color(255, 255, 255));
        jTextTitular.setForeground(new java.awt.Color(51, 51, 51));
        jTextTitular.setBorder(null);
        jTextTitular.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextTitularFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextTitularFocusLost(evt);
            }
        });
        bg.add(jTextTitular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseClicked
        MainManager.quit();
    }//GEN-LAST:event_txtexitMouseClicked

    private void txtexitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseEntered
        txtexit.setForeground(Color.white);
    }//GEN-LAST:event_txtexitMouseEntered

    private void txtexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtexitMouseExited
        txtexit.setForeground(Color.black);
    }//GEN-LAST:event_txtexitMouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed
    
    
    
    private void flechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_flechaMouseClicked
        String titular = jTextTitular.getText();
        String numero = jFormattedNumero.getText();
        String caducidad = jFormattedCaducidad.getText();
        if( titular.equals("") || numero.equals("    -    -    -    ") || caducidad.equals("  /  ")){
            JOptionPane.showMessageDialog(this, "Introduzca todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Tarjeta tarjeta = new Tarjeta(titular,numero,caducidad);
        String mensaje = MainManager.verificaTarjeta(tarjeta);
        if(!mensaje.equals("")){
            JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_flechaMouseClicked

    private void jFormattedNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedNumeroActionPerformed
    }//GEN-LAST:event_jFormattedNumeroActionPerformed

    private void jFormattedCaducidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedCaducidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedCaducidadActionPerformed

    private void jTextTitularFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTitularFocusGained
    }//GEN-LAST:event_jTextTitularFocusGained

    private void jTextTitularFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextTitularFocusLost
    }//GEN-LAST:event_jTextTitularFocusLost

    private void jFormattedNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedNumeroFocusGained
    }//GEN-LAST:event_jFormattedNumeroFocusGained

    private void jFormattedNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedNumeroFocusLost
    }//GEN-LAST:event_jFormattedNumeroFocusLost

    private void jFormattedCaducidadFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedCaducidadFocusGained
    }//GEN-LAST:event_jFormattedCaducidadFocusGained

    private void jFormattedCaducidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedCaducidadFocusLost
    }//GEN-LAST:event_jFormattedCaducidadFocusLost
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTarjeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroTarjeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel exitpanel;
    private javax.swing.JLabel flecha;
    private javax.swing.JPanel header;
    private javax.swing.JFormattedTextField jFormattedCaducidad;
    private javax.swing.JFormattedTextField jFormattedNumero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextTitular;
    private javax.swing.JLabel javaeatlogo1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JLabel txtCaducidad;
    private javax.swing.JLabel txtIBAN;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtTarjeta;
    private javax.swing.JLabel txtexit;
    // End of variables declaration//GEN-END:variables
}
