/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.FormatStyle;
import javax.swing.JPanel;
import javax.swing.JTextArea;


public class TemplateComentario extends javax.swing.JPanel {

    /**
     * Creates new form TemplateComentario
     */
    public TemplateComentario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        opinion = new javax.swing.JTextArea();
        titulo = new javax.swing.JLabel();
        puntuacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1058, 200));
        setMinimumSize(new java.awt.Dimension(1058, 200));
        setPreferredSize(new java.awt.Dimension(1058, 200));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opinion.setEditable(false);
        opinion.setBackground(new java.awt.Color(255, 255, 255));
        opinion.setColumns(45);
        opinion.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        opinion.setForeground(new java.awt.Color(51, 51, 51));
        opinion.setLineWrap(true);
        opinion.setRows(1);
        opinion.setText("Se muestran las opiniones de Burger King, que se encuentra en la provincia de Comunidad de Madrid y se incluye en la categoría de Restaurantes.La descripción del negocio es Esta empresa se desempeña en la siguiente industria: Restaurantes.\nActualmente, está valorado con una puntuación de 4.6 sobre 5, con una valoración basada en 5 opiniones. La valoración es muy positiva, teniendo en cuenta que se basa en un número muy superior a la media en cuanto a cantidad de valoraciones. De manera habitual, como usuarios, solo puntuamos experiencias negativas o incidencias, así que cuando compartimos valoraciones positivas es que son muy especiales, y por ello, la fiabilidad es mayor.");
        opinion.setWrapStyleWord(true);
        opinion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        opinion.setMargin(new java.awt.Insets(2, 2, 2, 6));
        opinion.setMaximumSize(new java.awt.Dimension(1000, 250));
        opinion.setMinimumSize(new java.awt.Dimension(1000, 250));
        opinion.setPreferredSize(new java.awt.Dimension(1000, 250));
        bg.add(opinion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 110));

        titulo.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("TITLO DE OPINIÓN");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        puntuacion.setFont(new java.awt.Font("Roboto Condensed Light", 2, 20)); // NOI18N
        puntuacion.setForeground(new java.awt.Color(0, 0, 0));
        puntuacion.setText("Puntuación: 4");
        bg.add(puntuacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));
        bg.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 990, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public JPanel getPanelParent() {
	return bg;
    }

    public JTextArea getOpinion() {
	return opinion;
    }

    public void setTitulo(String string) {
	titulo.setText(string);
    }

    public void setPuntuacion(int numero) {
	puntuacion.setText("Puntuación: " + numero);
    }
    
    public void setOpinion(String texto){
        opinion.setText(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea opinion;
    private javax.swing.JLabel puntuacion;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
