/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.CarritoCompra;
import com.clases.Catering;
import com.clases.Cliente;
import com.clases.Comida;
import com.clases.MainManager;
import com.clases.Menu;
import com.clases.Restaurante;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import com.interfaz.VerRestaurante;


public class TemplateCatering extends javax.swing.JPanel {

    private int cantidad = 0;
    private String servicioCatering;
    private CarritoCompra carrito;
    private Catering cat;
    private VerRestaurante padre;

    /**
     * Creates new form TemplateComida
     */
    public TemplateCatering(VerRestaurante padre) {
        

        initComponents();
        jScrollPane1.setVisible(false);
        this.carrito = MainManager.getCarritoCompra();
        this.padre = padre;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        precio = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jCantidad = new javax.swing.JLabel();
        jButtonMenos = new javax.swing.JButton();
        jButtonMas = new javax.swing.JButton();
        titulo = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jComida = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(280, 335));
        setMinimumSize(new java.awt.Dimension(280, 335));
        setPreferredSize(new java.awt.Dimension(280, 335));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        precio.setFont(new java.awt.Font("Roboto Light", 2, 30)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        precio.setText("300€");
        precio.setToolTipText("");
        add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 30));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_1_re.png"))); // NOI18N
        add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));

        jCantidad.setFont(new java.awt.Font("Roboto Condensed Light", 0, 24)); // NOI18N
        jCantidad.setForeground(new java.awt.Color(102, 102, 102));
        jCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCantidad.setText("0");
        add(jCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 50, 30));

        jButtonMenos.setBackground(new java.awt.Color(255, 186, 186));
        jButtonMenos.setFont(new java.awt.Font("Roboto Condensed Light", 1, 36)); // NOI18N
        jButtonMenos.setForeground(new java.awt.Color(51, 51, 51));
        jButtonMenos.setText("-");
        jButtonMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosActionPerformed(evt);
            }
        });
        add(jButtonMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 30, 30));

        jButtonMas.setBackground(new java.awt.Color(206, 255, 206));
        jButtonMas.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        jButtonMas.setForeground(new java.awt.Color(51, 51, 51));
        jButtonMas.setText("+");
        jButtonMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMasActionPerformed(evt);
            }
        });
        add(jButtonMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 30, 30));

        titulo.setEditable(false);
        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setColumns(20);
        titulo.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setRows(5);
        titulo.setText("SERVICIO CAMAREROS");
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 250, 20));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 160));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jComida.setEditable(false);
        jComida.setBackground(new java.awt.Color(255, 255, 255));
        jComida.setColumns(20);
        jComida.setForeground(new java.awt.Color(51, 51, 51));
        jComida.setRows(5);
        jComida.setBorder(null);
        jScrollPane1.setViewportView(jComida);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 240, 60));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosActionPerformed
        restCantidad();
    }//GEN-LAST:event_jButtonMenosActionPerformed

    private void jButtonMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMasActionPerformed
        addCantidad();
    }//GEN-LAST:event_jButtonMasActionPerformed

    public void setImage(ImageIcon image) {
        icon.setIcon(image);
    }
    
    public void setServicio(String servicio){
        this.servicioCatering = servicio;
    }
    
    public void setComida(String comida) {
        jScrollPane1.setVisible(true);
        jComida.setLineWrap(true);
        jComida.setWrapStyleWord(true);
        jComida.setText(comida);
    }

    public void setPrecio(double precio1) {
        
        precio.setText(String.valueOf(precio1) + "€");
    }

    public void setTitulo(String title) {
        titulo.setText(title);
    }

    public JLabel getIcon() {
        return icon;
    }

    public void addCantidad() {
        if (cantidad < 1) {
            cantidad += 1;
            jCantidad.setText(String.valueOf(cantidad));
            carrito.addCatering(servicioCatering);
            padre.actualizarListaCarrito(carrito);
        } else {
            JOptionPane.showMessageDialog(this, "Solo se puede añadir un servicio", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }

    public void restCantidad() {

        if (cantidad > 0) {
            cantidad -= 1;
            jCantidad.setText(String.valueOf(cantidad));
            carrito.getCatering().remove(servicioCatering);
            padre.actualizarListaCarrito(carrito);
        } else {
            JOptionPane.showMessageDialog(this, "No se pueden quitar más servicios", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void setImageFromPath(String path) {
        ImageIcon imagen = Comida.resizedIcon(icon.getBounds().width, icon.getBounds().height, path);
        icon.setIcon(imagen);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JButton jButtonMas;
    private javax.swing.JButton jButtonMenos;
    private javax.swing.JLabel jCantidad;
    private javax.swing.JTextArea jComida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel precio;
    private javax.swing.JTextArea titulo;
    // End of variables declaration//GEN-END:variables
}
