/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;


public class TemplateCarrito extends javax.swing.JPanel {
    
    private String servicio;
    
    /**
     * Creates new form TemplateCarrito
     */
    public TemplateCarrito() {
        initComponents();
    }
    
    public void setPrecio(double precio1) {
        precio.setText(String.format("%.2f%n",precio1) + "€");
    }

    public void setTitulo(String title) {
        titulo.setText(title);
    }
    
    public void setServicio(String title){
        this.servicio = title;
        titulo.setText("Servicio " + title);
    }
    
    public void setCantidad(int n){
        cantidad.setText("x" + n);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        cantidad = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        titulo = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(300, 70));
        setMinimumSize(new java.awt.Dimension(300, 70));

        bg.setBackground(new java.awt.Color(255, 153, 102));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cantidad.setFont(new java.awt.Font("Roboto Light", 2, 30)); // NOI18N
        cantidad.setForeground(new java.awt.Color(51, 51, 51));
        cantidad.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cantidad.setText("x1");
        cantidad.setToolTipText("");
        bg.add(cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 60, -1));

        precio.setFont(new java.awt.Font("Roboto Light", 2, 26)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 0, 0));
        precio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        precio.setText("3.99€");
        precio.setToolTipText("");
        bg.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 120, 20));

        titulo.setEditable(false);
        titulo.setBackground(new java.awt.Color(255, 153, 102));
        titulo.setColumns(20);
        titulo.setFont(new java.awt.Font("Roboto Condensed", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setRows(5);
        titulo.setText("CACHO POWER ");
        bg.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel cantidad;
    private javax.swing.JLabel precio;
    private javax.swing.JTextArea titulo;
    // End of variables declaration//GEN-END:variables
}
