/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.interfaz;

import com.clases.MainManager;
import com.clases.Restaurante;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;


public class TemplateRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form TemplateRestaurante
     */
    public TemplateRestaurante() {
        initComponents();
        
    }
    
    public void setImage(ImageIcon image){
	icon.setIcon(image);
    }
    
    public void setProduct(Restaurante restaurante){
	this.restaurante = restaurante;
    }
    
    
    public void setInformacion(double calificacionMedia, String especialidad, double gastosEnvio){
        if (calificacionMedia <= 1.5){
            txtCalificacion.setForeground(Color.red);
        }else if(calificacionMedia <= 3.0){
            txtCalificacion.setForeground(Color.orange);
        }else{
            txtCalificacion.setForeground(Color.green);
        }
        txtCalificacion.setText(calificacionMedia + "");
        txtEspecialidad.setText(especialidad);
        txtGastosEnvio.setText(gastosEnvio + "€");
    }
    
    public void setTiempo(int minutos){
        tiempoEnvio.setText(minutos + " min");
    }
    
    public void setTitulo(String title){
        titulo.setText(title);
    }
    
    public JLabel getIcon(){
        return icon;
    }
    
    public void setImageFromPath(String path){
        ImageIcon imagen = Restaurante.resizedIcon(icon.getBounds().width, icon.getBounds().height, path);
        icon.setIcon(imagen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        icon = new javax.swing.JLabel();
        txtCalificacion = new javax.swing.JLabel();
        titulo = new javax.swing.JTextArea();
        tiempoEnvio = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtGastosEnvio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(370, 230));
        setMinimumSize(new java.awt.Dimension(370, 230));
        setPreferredSize(new java.awt.Dimension(370, 230));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/klipartz.com (1).png"))); // NOI18N

        txtCalificacion.setFont(new java.awt.Font("Roboto Light", 0, 19)); // NOI18N
        txtCalificacion.setForeground(new java.awt.Color(153, 153, 153));
        txtCalificacion.setText("4.9 ");

        titulo.setEditable(false);
        titulo.setBackground(new java.awt.Color(255, 255, 255));
        titulo.setColumns(20);
        titulo.setFont(new java.awt.Font("Roboto Condensed Light", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setRows(5);
        titulo.setText("VIPS LA GARENA");

        tiempoEnvio.setFont(new java.awt.Font("Roboto Light", 0, 19)); // NOI18N
        tiempoEnvio.setForeground(new java.awt.Color(51, 51, 51));
        tiempoEnvio.setText("99 min");

        txtEspecialidad.setFont(new java.awt.Font("Roboto Light", 0, 19)); // NOI18N
        txtEspecialidad.setForeground(new java.awt.Color(51, 51, 51));
        txtEspecialidad.setText("Internacional");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/circulo.png"))); // NOI18N

        txtGastosEnvio.setFont(new java.awt.Font("Roboto Light", 0, 19)); // NOI18N
        txtGastosEnvio.setForeground(new java.awt.Color(51, 51, 51));
        txtGastosEnvio.setText("10€ ");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/otro/circulo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCalificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGastosEnvio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tiempoEnvio)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(icon, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEspecialidad)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tiempoEnvio)
                                .addComponent(txtGastosEnvio))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)))
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        MainManager.showVerRestaurante(restaurante);
    }//GEN-LAST:event_formMouseClicked

    
    private boolean isModifiable;
    private Restaurante restaurante;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel tiempoEnvio;
    private javax.swing.JTextArea titulo;
    private javax.swing.JLabel txtCalificacion;
    private javax.swing.JLabel txtEspecialidad;
    private javax.swing.JLabel txtGastosEnvio;
    // End of variables declaration//GEN-END:variables
}
